/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "var(--color-outline)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-secondary-fixed": "#241a00",
        "tertiary": "#162839",
        "on-tertiary-fixed": "#091d2e",
        "on-tertiary-container": "#96a9be",
        "on-error-container": "var(--color-on-error-container)",
        "tertiary-fixed-dim": "#b5c8df",
        "primary-container": "var(--color-primary-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-primary-fixed-variant": "#8f0f07",
        "error-container": "var(--color-error-container)",
        "on-background": "var(--color-on-background)",
        "secondary-fixed-dim": "#e9c349",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#410000",
        "primary-fixed": "#ffdad4",
        "on-primary-container": "var(--color-on-primary-container)",
        "inverse-surface": "#2f3130",
        "inverse-primary": "#ffb4a8",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-surface": "var(--color-on-surface)",
        "on-secondary": "var(--color-on-secondary)",
        "error": "var(--color-error)",
        "secondary-fixed": "#ffe088",
        "surface-tint": "#b22b1d",
        "inverse-on-surface": "#f1f1ef",
        "primary": "var(--color-primary)",
        "tertiary-container": "#2c3e50",
        "on-secondary-fixed-variant": "#574500",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-error": "var(--color-on-error)",
        "surface-dim": "var(--color-surface-dim)",
        "primary-fixed-dim": "#ffb4a8",
        "tertiary-fixed": "#d1e4fb",
        "surface-bright": "var(--color-surface-bright)",
        "secondary": "var(--color-secondary)",
        "surface": "var(--color-surface)",
        "surface-container": "var(--color-surface-container)",
        "on-tertiary-fixed-variant": "#36485b",
        "background": "var(--color-background)",
        "surface-variant": "var(--color-surface-container-highest)",
        "outline-variant": "var(--color-outline-variant)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-container": "var(--color-secondary-container)",
        "on-primary": "var(--color-on-primary)"
      },
      borderRadius: {
        // Keep Tailwind defaults (sm=2px, md=4px etc) but override specific ones
        "DEFAULT": "0.125rem",   // 2px  — base rounded
        "lg": "0.25rem",         // 4px  — rounded-lg (sharp, matching template)
        "xl": "0.5rem",          // 8px  — rounded-xl
        "2xl": "0.75rem",        // 12px
      },
      spacing: {
        "none": "0",
        "base": "4px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "40px",
        "xl": "64px",
        "gutter": "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-lg": ["Libre Caslon Text", "serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "headline-sm": ["Libre Caslon Text", "serif"],
        "headline-lg-mobile": ["Libre Caslon Text", "serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "body-sm": ["Work Sans", "sans-serif"],
        "label-lg": ["Work Sans", "sans-serif"],
        "label-md": ["Work Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
      }
    },
  },
  plugins: [],
}
