import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    // Auth & Common
    "welcome.back": "Welcome Back",
    "login.subtitle": "Sign in to manage your academic document requests",
    "email.address": "Email Address",
    "password": "Password",
    "forgot.password": "Forgot password?",
    "sign.in": "Sign In",
    "signing.in": "Signing In...",
    "new.to.bm": "New to Bishop Martin?",
    "create.account": "Create Parent Account",
    "having.trouble": "Having trouble? Contact the",
    "registrar.office": "Registrar's Office",
    "privacy.policy": "Privacy Policy",
    "terms.service": "Terms of Service",
    "copyright": "Bishop Martin Academy · Academic Document Request Portal",
    
    // Navigation & Layout
    "dashboard": "Dashboard",
    "requests": "Requests",
    "verification": "Verification",
    "profile": "Profile",
    "settings": "Settings",
    "logout": "Logout",
    "users": "Users",
    "admin.portal": "Admin Portal",
    "staff.portal": "Staff Portal",
    "my.profile": "My Profile",
    "view.profile": "View Profile",
    "parent.permissions.na": "Portal permissions are not applicable for parent accounts.",
    "back": "Back",
    
    // Dashboard & Actions
    "identity.verified": "Identity Verified",
    "identity.unverified": "Identity Unverified",
    "quick.actions": "Quick Actions",
    "new.request": "New Request",
    "identity.verification": "Identity Verification",
    "registrar.support": "Registrar Support",
    "recent.requests": "Recent Requests",
    "no.requests": "No requests found.",
    "document.type": "Document Type",
    "student": "Student",
    "date": "Date",
    "status": "Status",
    "actions": "Actions",
    
    // Request Flow
    "step.document": "Document",
    "step.student": "Student",
    "step.delivery": "Delivery",
    "step.review": "Review",
    "select.doc.type": "Select Document Type",
    "official.transcript": "Official Transcript",
    "enrollment.letter": "Letter of Enrollment",
    "graduation.cert": "Graduation Certificate",
    "deans.letter": "Dean's Letter",
    "other.special": "Other/Special Request",
    "student.info": "Student Information",
    "full.name": "Full Name",
    "student.id": "Student ID",
    "dob": "Date of Birth",
    "grade": "Grade",
    "relationship": "Relationship",
    "delivery.processing": "Delivery & Processing",
    "delivery.method": "Delivery Method",
    "digital.copy": "Digital Copy (PDF via Email)",
    "physical.pickup": "Physical Pickup (In Person)",
    "processing.speed": "Processing Speed",
    "standard.speed": "Standard Processing",
    "expedited.speed": "Expedited (+ $25.00)",
    "urgent.speed": "Urgent Priority (+ $50.00)",
    "fee.breakdown": "Fee Breakdown",
    "base.fee": "Base Fee",
    "delivery.fee": "Delivery",
    "speed.fee": "Processing Speed",
    "total.fee": "Total",
    "review.sign": "Review & Authorization",
    "consent.text": "By signing below, I certify that I am the legal parent/guardian of the student listed above and authorize the release of these academic documents.",
    "sign.here": "Sign in the box below",
    "clear": "Clear",
    "submit.request": "Submit Authorization",
    "submitting": "Submitting...",
    
    // Statuses
    "pending": "Pending",
    "approved": "Approved",
    "processing": "Processing",
    "ready": "Ready",
    "issued": "Issued",
    "action.required": "Action Required",
    "rejected": "Rejected",
    
    // Settings / Dark Mode / Lang
    "theme": "Theme",
    "dark.mode": "Dark Mode",
    "light.mode": "Light Mode",
    "language": "Language",
    "english": "English",
    "spanish": "Spanish",
    "save.changes": "Save Changes",
    "queue": "Queue",
    "payments": "Payments",
    "sign.out": "Sign Out",
    "staff.access": "Staff Access",
    "super.admin": "Super Admin",
    "verify": "Verify",
    "hub": "Hub",
    "history": "History",
    "clear.filters": "Clear Filters",
    "loading.queue": "Loading queue...",
    "search.placeholder": "Search by student name, ID, or reference...",
    "all.doc.types": "All Document Types",
    "status.all": "Status: All",
    "date.received": "Date Received",
    "student.details": "Student Details",
    "no.matching.requests": "No requests found matching your filters.",
    "replacement.diploma": "Replacement Diploma",
    "user.mgmt.dir": "User Management Directory",
    "user.mgmt.subtitle": "Search and manage institutional access for staff, students, and legal guardians.",
    "invite.new.user": "Invite New User",
    "search.placeholder.user": "Name, Email, or ID Number...",
    "user.role": "User Role",
    "account.status": "Account Status",
    "all.statuses": "All Statuses",
    "active": "Active",
    "deactivated": "Deactivated",
    "last.active": "Last Active",
    "any.time": "Any Time",
    "last.7.days": "Last 7 Days",
    "requests.in.queue": "request(s) in queue",
    "request.management": "Request Management",
    "requests.subtitle": "Official document processing queue. Maintain institutional standards through meticulous verification.",
    "export.queue": "Export Queue",
    "search.student": "Search student...",
    "filter.status": "Filter Status",
    "filter.type": "Filter Type",
    
    // SuperAdmin
    "superadmin.console": "SuperAdmin Console",
    "sys.governance": "High-level system governance, server registry, and operational control.",
    "total.users": "Total Users",
    "parents": "Parents",
    "staff": "Staff",
    "super.admins": "Super Admins",
    "staff.registry": "Staff Registry",
    "provision.staff": "Provision Staff",
    "public.users": "Public Users",
    "search.directory": "Search Directory",
    "network.id": "Network ID",
    "identity": "Identity",
    "security.auth": "Security Auth",
    "node.termination": "Node Termination",
    "all.accounts": "All accounts",
    "registered.parents": "Registered parents",
    "admins.viewers": "Admins & viewers",
    "root.access": "Root access",
    "filter.staff": "Filter staff members...",
    "filter.public": "Filter public parent users...",
    "provision.staff.node": "Provision New Staff Node",
    "onboard.staff.member": "Onboard a new administrative staff member",
    "inst.email": "Institutional Email",
    "access.level": "Access Level",
    "level.admin": "Level 3: Admin",
    "level.viewer": "Level 2: Viewer (Read-only)",
    "level.superadmin": "Level 4: Super Admin (Root)",
    "temp.password": "Temporary Password",
    "creating.account": "Creating Account...",
    "deploy.active.account": "Deploy Active Account",
    "no.staff.nodes": "No staff nodes discovered in this sector.",
    "no.parent.users": "No parent user accounts discovered.",
    "override.password": "Override Password",
    "delete.node": "Delete Node",
    "verified": "Verified",
    "unverified": "Unverified",
    "meta.details": "Meta Details",
    "no.matching.users": "No matching user accounts discovered.",
    "password.override": "Password Override",
    "force.password.overwrite": "Forcefully overwrite password credentials for user:",
    "override.warning.msg": "This operation permanently overwrites the database security hash. The user will need to log in with this temporary password and update it immediately.",
    "temp.password.chars": "Temporary Password (min. 6 chars)",
    "executing.reset": "Executing Reset...",
    "execute.override": "Execute Override",
    "override": "Override",
    "delete": "Delete",
    "user.mgmt.dir": "User Management Directory",
    "user.mgmt.subtitle": "Search and manage institutional access for staff, students, and legal guardians.",
    "invite.new.user": "Invite New User",
    "search.placeholder.user": "Name, Email, or ID Number...",
    "user.role": "User Role",
    "account.status": "Account Status",
    "all.statuses": "All Statuses",
    "active": "Active",
    "deactivated": "Deactivated",
    "last.active": "Last Active",
    "any.time": "Any Time",
    "last.7.days": "Last 7 Days",
    "last.30.days": "Last 30 Days",
    "over.6.months": "Over 6 Months",
    "reset.filters": "Reset Filters",
    "full.directory": "Full Directory (Recent Updates)",
    "role": "Role",
    "last.login": "Last Login",
    "user.not.found": "User not found.",
    "user.detail": "User Detail",
    "back.to.users": "Back to Users",
    "account.info": "Account Information",
    "danger.zone": "Danger Zone",
    "deactivate.account": "Deactivate Account",
    "portal.permissions": "Portal Permissions",
    "save.permissions": "Save Permissions",
    "permissions.updated": "Permissions Updated",
    "permissions.success.msg": "The user's portal permissions have been saved and will take effect on their next login.",
    "back.to.user": "Back to User",
    "all.users": "All Users",
    "invite.user.title": "Invite Portal User",
    "invite.user.subtitle": "Send an invitation to grant access to the Bishop Martin administrative portal.",
    "full.name.label": "Full Name *",
    "email.address.label": "Email Address *",
    "phone.number.label": "Phone Number",
    "portal.role.label": "Portal Role *",
    "dept.title.label": "Department / Title",
    "role.info.text": "Staff: Can process requests and verify documents. Admin: Can manage users and permissions. Super Admin: Full system access.",
    "send.invitation": "Send Invitation",
    "sending.invitation": "Sending...",
    "invitation.sent": "Invitation Sent!",
    "invitation.sent.to": "An invitation email has been dispatched to",
    "next.steps": "Next Steps",
    "invite.another": "Invite Another",
    "invite.step1": "The invitee will receive an email with a secure setup link.",
    "invite.step2": "They must create a password and complete account setup.",
    "invite.step3": "Permissions can be adjusted any time from User Detail.",
    "requests": "Requests",
    "payments": "Payments",
    "administration": "Administration",
    "view_requests": "View All Requests",
    "manage_requests": "Process & Update Requests",
    "approve_documents": "Approve & Release Documents",
    "view_payments": "View Payment Records",
    "verify_payments": "Verify Bank Transfers",
    "view_users": "View User Directory",
    "manage_users": "Create & Edit Users",
    "manage_permissions": "Manage Permissions",
    "view_verifications": "View ID Verifications",
    "approve_verifications": "Approve ID Verifications",
    "changes.applied": "Changes applied instantly to database",
    "user.notified.email": "User notified via email",
    "audit.log.updated": "Audit log updated",
    "cancel": "Cancel",
    "saving": "Saving...",
    "saved": "Saved",
    "never": "Never",
    "loading": "Loading...",
    "no.users": "No users found.",
    "pending.verification": "Pending Verification",
    "more.options": "More options",
    "admin.overview": "Administrative Overview",
    "registrar.control.panel": "Registrar Control Panel",
    "pending.requests": "Pending Requests",
    "avg.lead.time": "Avg. Lead Time",
    "issued.today": "Issued Today",
    "high.urgency": "High Urgency",
    "urgency.queue": "Urgency Queue",
    "view.all.queue": "View All Queue",
    "requester": "Requester",
    "sla.status": "SLA Status",
    "action": "Action",
    "process.next.queue": "Process Next in Queue",
    "review.id.verifications": "Review ID Verifications",
    "pending.payments": "Pending Payments",
    "system.status": "System Status",
    "document.portal": "Document Portal",
    "payment.gateway": "Payment Gateway",
    "email.notifications": "Email Notifications",
    "online": "Online",
    "days": "Days",
    
    // Parent Dashboard Additions
    "parent.portal": "Parent Portal",
    "good.morning": "Good morning",
    "good.afternoon": "Good afternoon",
    "good.evening": "Good evening",
    "parent.dashboard.subtitle": "Manage academic document requests for your students at Bishop Martin Academy.",
    "identity.status": "Identity Status",
    "verification.active": "Verification active · Valid",
    "request.doc": "Request a Document",
    "request.doc.desc": "Transcript, Certificate & more",
    "upload.id.desc": "Upload ID document",
    "email.office": "Email our office",
    "need.help": "Need Help?",
    "office.hours.desc": "Office hours: Mon–Fri, 8:00 AM – 4:00 PM (BZT). Turnaround: 3–5 business days.",
    "call.registrar": "Call the Registrar",
    "my.document.requests": "My Document Requests",
    "view.all": "View All",
    "ref": "Ref",
    "document": "Document",
    "amount": "Amount",
    "no.requests.yet": "No requests yet",
    "make.first.request": "Make your first request",

    // Additional translations
    "back.request.summary": "Back to Request Summary",
    "complete.payment": "Complete Your Payment",
    "payment.instructions": "Please finalize your document request by initiating a bank transfer. Use the details below to ensure prompt processing of your academic records.",
    "bank.transfer.details": "Bank Transfer Details",
    "bank.name": "Bank Name",
    "account.holder": "Account Holder",
    "account.number": "Account Number",
    "branch.swift": "Branch / SWIFT",
    "req.ref.memo": "Required Reference Memo",
    "ref.memo.desc": "You MUST include your request reference number in the transfer description/memo field to avoid delays.",
    "next.steps": "Next Steps",
    "step.initiate": "Initiate Transfer",
    "step.initiate.desc": "Use your banking app or visit a Belize Bank branch to send the total amount specified to the account above.",
    "step.upload": "Upload Receipt",
    "step.upload.desc": "Once completed, upload a clear PDF or photo of the transaction confirmation in the next step.",
    "step.verify": "Verification",
    "step.verify.desc": "Our bursar's office will verify the funds within 2–3 business days.",
    "request.summary": "Request Summary",
    "doc.fee": "Document Fee",
    "doc.fee.desc": "Academic document requested",
    "processing.fee": "Processing Fee",
    "processing.fee.desc": "Selected processing speed",
    "total.due": "Total Amount Due",
    "confirm.initiated": "Confirm Transfer Initiated",
    "confirm.initiated.desc": "Clicking this notifies our staff that funds are incoming. You will be prompted to upload proof next.",
    "copied": "copied!",
    "back.signin": "Back to Sign In",
    "reset.password": "Reset Password",
    "reset.pw.desc": "Enter your email and we will send you a reset link.",
    "send.reset.link": "Send Reset Link",
    "check.email": "Check Your Email",
    "reset.link.sent": "A reset link has been sent to",
    "check.inbox.desc": "Check your inbox and follow the instructions.",
    "create.new.pw": "Create New Password",
    "strong.pw.desc": "Choose a strong password for your Bishop Martin account.",
    "new.password": "New Password",
    "confirm.password": "Confirm Password",
    "pw.mismatch": "Passwords do not match.",
    "resetting": "Resetting...",
    "legal.acknowledgement": "Legal Acknowledgement",
    "legal.text.1": "I, the undersigned parent/guardian, hereby authorize Bishop Martin Academy to release the requested academic records and formal documentation to the specified recipients. I understand that this digital signature carries the same legal weight and institutional validity as a handwritten signature under the Electronic Transactions Act.",
    "legal.text.2": "I certify that all information provided in this request is accurate and that I have the legal authority to authorize the release of these records. I acknowledge that the processing of this request may involve administrative verification and that the institution reserves the right to withhold documentation in cases of outstanding financial obligations or incomplete verification.",
    "legal.text.3": "By proceeding with this digital signature, I consent to the storage and processing of my personal data for the purpose of fulfilling this documentation request in accordance with the institution's privacy policy and academic governance standards.",
    "legal.agree": "I have read, understood, and agree to the terms of this Legal Acknowledgement and Authorization.",
    "sig.pad": "Digital Signature Pad",
    "sig.instruction": "Sign here with mouse or touch",
    "sig.name.label": "Full Legal Name of Signatory",
    "sig.name.placeholder": "Enter your full name as it appears on your ID",
    "cancel.request": "Cancel Request",
    "confirm.authorize": "Confirm & Authorize",
    "authorized": "Authorized",
    "processing.time": "Processing Time",
    "processing.time.desc": "Documents are typically issued within 3–5 business days after signature verification.",
    "secure.transmission": "Secure Transmission",
    "secure.transmission.desc": "Your authorization is encrypted and stored in the school's high-security administrative ledger.",
    "request.submitted": "Request Submitted!",
    "request.submitted.desc": "Your academic document request has been received and is now pending review by the Registrar's Office.",
    "ref.num": "Reference Number",
    "save.ref.desc": "Save this number to track your request status.",
    "what.next": "What Happens Next",
    "timeline.payment": "Payment Verification",
    "timeline.payment.desc": "Our bursar's office confirms your bank transfer (2–3 business days).",
    "timeline.processing": "Document Processing",
    "timeline.processing.desc": "The Registrar reviews and prepares your document.",
    "timeline.delivery": "Delivery / Notification",
    "timeline.delivery.desc": "You'll receive an email when your document is ready.",
    "return.dashboard": "Return to Dashboard",
    "upload.payment.receipt": "Upload Payment Receipt",
    "upload.receipt.desc": "Upload clear proof of your bank transfer. Accepted formats: PDF, JPG, PNG (max 10 MB).",
    "txn.ref.num": "Transaction Reference Number",
    "txn.ref.desc": "This is shown in your bank transaction history or confirmation SMS.",
    "drag.drop.receipt": "Drag & drop your receipt here",
    "click.browse": "or click to browse files",
    "err.allowed.formats": "Only PDF, JPG, or PNG files are accepted.",
    "err.max.size": "File must be under 10 MB.",
    "err.upload.receipt": "Please upload your payment receipt.",
    "uploaded.success": "Uploaded Successfully",
    "submit.receipt": "Submit Receipt",
    "photo.tips": "Photo Tips",
    "tip.corners": "Capture All Corners",
    "tip.corners.desc": "Ensure all four corners of the receipt are visible.",
    "tip.glare": "Avoid Glare & Shadows",
    "tip.glare.desc": "Take the photo in good lighting, no reflections.",
    "tip.level": "Keep It Level",
    "tip.level.desc": "Hold the camera parallel to the document.",
    "tip.secure": "Secure Encryption",
    "tip.secure.desc": "Your upload is protected with 256-bit encryption.",
    "payment.sent.to": "Payment sent to:",
    "id.verification": "Identity Verification",
    "id.ver.desc": "Upload a clear photo of your government-issued ID. This is required once for all future document requests.",
    "upload.id.doc": "Upload ID Document",
    "passport": "Passport",
    "national.id": "National ID",
    "drivers.license": "Driver's License",
    "voters.id": "Voter's ID",
    "pos.id.frame": "Position your ID within the frame",
    "photo.guidelines": "Photo Guidelines",
    "guideline.corners": "Capture All Corners",
    "guideline.corners.desc": "Ensure all four edges are visible and unclipped.",
    "guideline.glare": "Avoid Glare & Shadows",
    "guideline.glare.desc": "Good, even lighting with no bright reflections.",
    "guideline.level": "Keep It Level",
    "guideline.level.desc": "Camera parallel to the document, no tilt.",
    "guideline.secure": "Encrypted & Secure",
    "guideline.secure.desc": "Your ID is processed securely and never shared.",
    "err.allowed.id.formats": "Only JPG, PNG, HEIC, or PDF files are accepted.",
    "err.max.id.size": "File must be under 15 MB.",
    "err.upload.id": "Please upload your identity document.",
    "verify.continue": "Verify & Continue",
    "processing.verification": "Processing Verification",
    "stage.receiving": "Receiving document...",
    "stage.extracting": "Extracting identity data...",
    "stage.crossref": "Cross-referencing records...",
    "stage.finalizing": "Finalizing verification...",
    "percent.complete": "complete",
    "process.stay.desc": "Please stay on this page. This may take a moment while we securely verify your identity document.",
    "verification.submitted": "Verification Submitted",
    "ver.submitted.desc": "Your identity document has been securely received and is pending review by the Registrar's administrative team.",
    "what.expect": "What to Expect",
    "expect.review": "Review Time",
    "expect.review.desc": "Identity documents are reviewed within 1–2 business days.",
    "expect.confirm": "Email Confirmation",
    "expect.confirm.desc": "You'll receive confirmation at your registered email address.",
    "expect.security": "Data Security",
    "expect.security.desc": "Your document is processed in a secure environment and never shared.",
    "pending.admin.review": "Pending Administrative Review",
    "my.requests": "My Requests",
    "request.history": "Request History",
    "all.requests.desc": "All document requests submitted for your students.",
    "search.requests": "Search requests...",
    "no.matching.requests": "No matching requests.",
    "submitted": "Submitted",
    "fee": "Fee",
    "request.detail": "Request Detail",
    "request.progress": "Request Progress",
    "payment.verified": "Payment Verified",
    "delivered": "Delivered",
    "delivery": "Delivery",
    "request.details": "Request Details",
    "student.name": "Student Name",
    "grade.year": "Grade / Year",
    "recipient": "Recipient",
    "date.submitted": "Date Submitted",
    "total.fee": "Total Fee",
    "action.required.msg": "Action Required — Please Check Email",
    "flagged.msg": "The Registrar has flagged your request. Please check your email for details or contact the Registrar Office.",
    "contact.registrar": "Contact Registrar",
    "ready.pickup.msg": "Your document is ready. Please visit the Registrar Office during office hours (Mon–Fri 8AM–4PM) with a valid ID.",
    "payment.summary": "Payment Summary",
    "total.paid": "Total Paid",
    "email.us": "Email Us",
    "call.us": "Call Us",
    "pending.payments.queue": "Pending Payments Queue",
    "payments.queue.desc": "Review bank transfer receipts and verify payment for pending document requests.",
    "no.pending.payments": "No pending payments",
    "verify.payment": "Verify Payment",
    "view.receipt": "View Receipt",
    "reg.audit.notes": "Registrar Audit Notes",
    "audit.notes.placeholder": "Add internal notes about this request (document condition, verification status, correspondence, etc.)...",
    "visible.staff.only": "Notes are visible to staff only.",
    "update.status": "Update Status",
    "save.status.change": "Save Status Change",
    "approve.release": "Approve & Release Document",
    "flag.correction": "Flag for Correction",
    "sla.compliance": "SLA Compliance",
    "next.bus.day": "Next Business Day",
    "days.2_3": "2–3 Business Days",
    "days.5_7": "5–7 Business Days",
    "my.profile": "My Profile",
    "profile.desc": "Manage your account details and preferences.",
    "member.since": "Member Since",
    "email": "Email",
    "verification": "Verification",
    "active.verified": "Active · Verified",
    "edit.profile": "Edit Profile",
    "phone.number": "Phone Number",
    "email.unchangeable": "Email cannot be changed. Contact Registrar for updates.",
    "security.password": "Security & Password",
    "sec.pw.desc": "Keep your account secure by using a strong, unique password.",
    "change.password": "Change Password",
    "new.doc.request": "New Document Request",
    "choose.doc.desc": "Choose the academic document you need. Fees are in Belize Dollars (BZD).",
    "saved.students": "Saved Students",
    "or.manual.override": "Or enter manually to override:",
    "manual.fullName": "Full Name *",
    "manual.studentId": "Student ID *",
    "manual.dob": "Date of Birth",
    "manual.grade": "Year / Grade",
    "manual.relationship": "Your Relationship to Student *",
    "rel.parent": "Parent",
    "rel.guardian": "Legal Guardian",
    "rel.self": "Self (Alumni)",
    "rel.rep": "Authorized Representative",
    "choose.del.desc": "Choose how and how quickly you need your document.",
    "digital.delivery": "Digital Delivery",
    "pdf.sec.email": "PDF via secure email",
    "physical.copy": "Physical Copy",
    "pickup.postal": "Pickup or postal mail",
    "std.proc": "Standard Processing",
    "std.proc.desc": "5–7 business days",
    "exp.proc": "Expedited Processing",
    "exp.proc.desc": "2–3 business days",
    "urg.proc": "Urgent Processing",
    "urg.proc.desc": "Next business day",
    "where.send": "Where should we send the document?",
    "special.instructions": "Special Instructions (optional)",
    "special.notes.placeholder": "Any special notes for the Registrar's Office...",
    "doc.requested": "Document Requested",
    "review.submit": "Review & Submit",
    "review.desc": "Please verify all details before submitting your request.",
    "submitting.request": "Submitting...",
    "ready.pickup": "Ready for Pickup",
    "coming.soon": "Coming Soon",
    "under.development": "This section is under active development and will be available in an upcoming release.",
    "go.back": "Go Back",
    "cancelled": "Cancelled",
    "toast.approved": "Document approved & released!",
    "toast.flagged": "Request flagged for correction.",
    "toast.status.updated": "Status updated.",
    "drag.drop.id": "Drag & drop your ID here",
    "remove.reupload": "Remove and re-upload",
    "allowed.id.specs": "JPG · PNG · HEIC · PDF · Max 15 MB",
    "verifying": "Verifying...",
    "requester.notes": "Requester Notes",
    "request.not.found": "Request not found.",
    "preview.not.available": "Document preview not available in this view",
    "requester.notes": "Requester Notes",
    "user.id": "User ID",
    "phone": "Phone",
  },
  es: {
    // Auth & Common
    "welcome.back": "Bienvenido de Nuevo",
    "login.subtitle": "Inicie sesión para gestionar sus solicitudes de documentos académicos",
    "email.address": "Correo Electrónico",
    "password": "Contraseña",
    "forgot.password": "¿Olvidó su contraseña?",
    "sign.in": "Iniciar Sesión",
    "signing.in": "Iniciando Sesión...",
    "new.to.bm": "¿Nuevo en Bishop Martin?",
    "create.account": "Crear Cuenta de Padre",
    "having.trouble": "¿Tiene problemas? Contacte a la",
    "registrar.office": "Oficina del Registrador",
    "privacy.policy": "Política de Privacidad",
    "terms.service": "Términos de Servicio",
    "copyright": "Academia Bishop Martin · Portal de Solicitudes Académicas",
    
    // Navigation & Layout
    "dashboard": "Panel de Control",
    "requests": "Solicitudes",
    "verification": "Verificación",
    "profile": "Perfil",
    "settings": "Configuración",
    "logout": "Cerrar Sesión",
    "users": "Usuarios",
    "admin.portal": "Portal del Administrador",
    "staff.portal": "Portal del Personal",
    "my.profile": "Mi Perfil",
    "view.profile": "Ver Perfil",
    "parent.permissions.na": "Los permisos del portal no son aplicables para las cuentas de padres.",
    "back": "Atrás",
    
    // Dashboard & Actions
    "identity.verified": "Identidad Verificada",
    "identity.unverified": "Identidad Sin Verificar",
    "quick.actions": "Acciones Rápidas",
    "new.request": "Nueva Solicitud",
    "identity.verification": "Verificación de Identidad",
    "registrar.support": "Soporte del Registrador",
    "recent.requests": "Solicitudes Recientes",
    "no.requests": "No se encontraron solicitudes.",
    "document.type": "Tipo de Documento",
    "student": "Estudiante",
    "date": "Fecha",
    "status": "Estado",
    "actions": "Acciones",
    
    // Request Flow
    "step.document": "Documento",
    "step.student": "Estudiante",
    "step.delivery": "Envío",
    "step.review": "Revisión",
    "select.doc.type": "Seleccione el Tipo de Documento",
    "official.transcript": "Transcripción Oficial",
    "enrollment.letter": "Carta de Matrícula",
    "graduation.cert": "Certificado de Graduación",
    "deans.letter": "Carta del Decano",
    "other.special": "Otra Solicitud Especial",
    "student.info": "Información del Estudiante",
    "full.name": "Nombre Completo",
    "student.id": "ID de Estudiante",
    "dob": "Fecha de Nacimiento",
    "grade": "Grado",
    "relationship": "Parentesco",
    "delivery.processing": "Envío y Procesamiento",
    "delivery.method": "Método de Envío",
    "digital.copy": "Copia Digital (PDF por Correo)",
    "physical.pickup": "Recogida Física (En Persona)",
    "processing.speed": "Velocidad de Procesamiento",
    "standard.speed": "Procesamiento Estándar",
    "expedited.speed": "Expedito (+ $25.00)",
    "urgent.speed": "Prioridad Urgente (+ $50.00)",
    "fee.breakdown": "Desglose de Tarifas",
    "base.fee": "Tarifa Base",
    "delivery.fee": "Envío",
    "speed.fee": "Velocidad de Proceso",
    "total.fee": "Total",
    "review.sign": "Revisión y Autorización",
    "consent.text": "Al firmar a continuación, certifico que soy el padre/tutor legal del estudiante mencionado anteriormente y autorizo la divulgación de estos documentos académicos.",
    "sign.here": "Firme en el cuadro a continuación",
    "clear": "Limpiar",
    "submit.request": "Enviar Autorización",
    "submitting": "Enviando...",
    
    // Statuses
    "pending": "Pendiente",
    "approved": "Aprobado",
    "processing": "Procesando",
    "ready": "Listo",
    "issued": "Emitido",
    "action.required": "Acción Requerida",
    "rejected": "Rechazado",
    
    // Settings / Dark Mode / Lang
    "theme": "Tema",
    "dark.mode": "Modo Oscuro",
    "light.mode": "Modo Claro",
    "language": "Idioma",
    "english": "Inglés",
    "spanish": "Español",
    "save.changes": "Guardar Cambios",
    "queue": "Cola",
    "payments": "Pagos",
    "sign.out": "Cerrar Sesión",
    "staff.access": "Acceso de Personal",
    "super.admin": "Super Admin",
    "verify": "Verificar",
    "hub": "Inicio",
    "history": "Historial",
    "clear.filters": "Limpiar Filtros",
    "loading.queue": "Cargando cola...",
    "search.placeholder": "Buscar por nombre de estudiante, ID, o referencia...",
    "all.doc.types": "Todos los Tipos de Documento",
    "status.all": "Estado: Todos",
    "date.received": "Fecha Recibida",
    "student.details": "Detalles del Estudiante",
    "no.matching.requests": "No se encontraron solicitudes que coincidan con sus filtros.",
    "replacement.diploma": "Reemplazo de Diploma",
    "user.mgmt.dir": "Directorio de Gestión de Usuarios",
    "user.mgmt.subtitle": "Busque y gestione el acceso institucional para el personal, estudiantes y tutores legales.",
    "invite.new.user": "Invitar Nuevo Usuario",
    "search.placeholder.user": "Nombre, Correo o Número de ID...",
    "user.role": "Rol de Usuario",
    "account.status": "Estado de la Cuenta",
    "all.statuses": "Todos los Estados",
    "active": "Activo",
    "deactivated": "Desactivado",
    "last.active": "Última Actividad",
    "any.time": "Cualquier Momento",
    "last.7.days": "Últimos 7 Días",
    "requests.in.queue": "solicitud(es) en cola",
    "request.management": "Gestión de Solicitudes",
    "requests.subtitle": "Cola de procesamiento oficial de documentos. Mantenga los estándares institucionales mediante una verificación meticulosa.",
    "export.queue": "Exportar Cola",
    "search.student": "Buscar estudiante...",
    "filter.status": "Filtrar Estado",
    "filter.type": "Filtrar Tipo",
    "clear.filters": "Limpiar Filtros",
    
    // SuperAdmin
    "superadmin.console": "Consola de SuperAdmin",
    "sys.governance": "Gobernanza del sistema de alto nivel, registro de servidores y control operativo.",
    "total.users": "Usuarios Totales",
    "parents": "Padres",
    "staff": "Personal",
    "super.admins": "Super Administradores",
    "staff.registry": "Registro de Personal",
    "provision.staff": "Proveer Personal",
    "public.users": "Usuarios Públicos",
    "search.directory": "Buscar en el Directorio",
    "network.id": "ID de Red",
    "identity": "Identidad",
    "security.auth": "Aut. de Seguridad",
    "node.termination": "Terminación de Nodo",
    "all.accounts": "Todas las cuentas",
    "registered.parents": "Padres registrados",
    "admins.viewers": "Administradores y observadores",
    "root.access": "Acceso root",
    "filter.staff": "Filtrar miembros del personal...",
    "filter.public": "Filtrar usuarios públicos (padres)...",
    "provision.staff.node": "Proveer Nuevo Nodo de Personal",
    "onboard.staff.member": "Incorporar a un nuevo miembro del personal administrativo",
    "inst.email": "Correo Institucional",
    "access.level": "Nivel de Acceso",
    "level.admin": "Nivel 3: Administrador",
    "level.viewer": "Nivel 2: Observador (Solo lectura)",
    "level.superadmin": "Nivel 4: Super Administrador (Root)",
    "temp.password": "Contraseña Temporal",
    "creating.account": "Creando Cuenta...",
    "deploy.active.account": "Desplegar Cuenta Activa",
    "no.staff.nodes": "No se descubrieron nodos de personal en este sector.",
    "no.parent.users": "No se descubrieron cuentas de usuarios padres.",
    "override.password": "Anular Contraseña",
    "delete.node": "Eliminar Nodo",
    "verified": "Verificado",
    "unverified": "Sin Verificar",
    "meta.details": "Detalles Meta",
    "no.matching.users": "No se descubrieron cuentas de usuarios que coincidan.",
    "password.override": "Anulación de Contraseña",
    "force.password.overwrite": "Sobrescribir por la fuerza las credenciales de contraseña para el usuario:",
    "override.warning.msg": "Esta operación sobrescribe permanentemente el hash de seguridad de la base de datos. El usuario deberá iniciar sesión con esta contraseña temporal y actualizarla de inmediato.",
    "temp.password.chars": "Contraseña Temporal (mín. 6 caracteres)",
    "executing.reset": "Ejecutando Restablecimiento...",
    "execute.override": "Ejecutar Anulación",
    "override": "Anular",
    "delete": "Eliminar",
    "user.mgmt.dir": "Directorio de Gestión de Usuarios",
    "user.mgmt.subtitle": "Busque y gestione el acceso institucional para el personal, estudiantes y tutores legales.",
    "invite.new.user": "Invitar Nuevo Usuario",
    "search.placeholder.user": "Nombre, Correo o Número de ID...",
    "user.role": "Rol de Usuario",
    "account.status": "Estado de la Cuenta",
    "all.statuses": "Todos los Estados",
    "active": "Activo",
    "deactivated": "Desactivado",
    "last.active": "Última Actividad",
    "any.time": "Cualquier Momento",
    "last.7.days": "Últimos 7 Días",
    "last.30.days": "Últimos 30 Días",
    "over.6.months": "Más de 6 Meses",
    "reset.filters": "Restablecer Filtros",
    "full.directory": "Directorio Completo (Actualizaciones Recientes)",
    "role": "Rol",
    "last.login": "Último Inicio de Sesión",
    "user.not.found": "Usuario no encontrado.",
    "user.detail": "Detalle del Usuario",
    "back.to.users": "Volver a Usuarios",
    "account.info": "Información de la Cuenta",
    "danger.zone": "Zona de Peligro",
    "deactivate.account": "Desactivar Cuenta",
    "portal.permissions": "Permisos del Portal",
    "save.permissions": "Guardar Permisos",
    "permissions.updated": "Permisos Actualizados",
    "permissions.success.msg": "Los permisos del portal del usuario han sido guardados y tendrán efecto en su próximo inicio de sesión.",
    "back.to.user": "Volver al Usuario",
    "all.users": "Todos los Usuarios",
    "invite.user.title": "Invitar Usuario del Portal",
    "invite.user.subtitle": "Envíe una de invitación para otorgar acceso al portal administrativo de Bishop Martin.",
    "full.name.label": "Nombre Completo *",
    "email.address.label": "Dirección de Correo *",
    "phone.number.label": "Número de Teléfono",
    "portal.role.label": "Rol del Portal *",
    "dept.title.label": "Departamento / Cargo",
    "role.info.text": "Personal: Puede procesar solicitudes y verificar documentos. Admin: Puede gestionar usuarios y permisos. Super Admin: Acceso total al sistema.",
    "send.invitation": "Enviar Invitación",
    "sending.invitation": "Enviando...",
    "invitation.sent": "¡Invitación Enviada!",
    "invitation.sent.to": "Se ha enviado un correo electrónico de invitación a",
    "next.steps": "Próximos Pasos",
    "invite.another": "Invitar a Otro",
    "invite.step1": "El invitado recibirá un correo electrónico con un enlace de configuración seguro.",
    "invite.step2": "Deben crear una contraseña y completar la configuración de la cuenta.",
    "invite.step3": "Los permisos se pueden ajustar en cualquier momento desde el Detalle del Usuario.",
    "requests": "Solicitudes",
    "payments": "Pagos",
    "administration": "Administración",
    "view_requests": "Ver Todas las Solicitudes",
    "manage_requests": "Procesar y Actualizar Solicitudes",
    "approve_documents": "Aprobar y Emitir Documentos",
    "view_payments": "Ver Registros de Pago",
    "verify_payments": "Verificar Transferencias Bancarias",
    "view_users": "Ver Directorio de Usuarios",
    "manage_users": "Crear y Editar Usuarios",
    "manage_permissions": "Gestionar Permisos",
    "view_verifications": "Ver Verificaciones de Identidad",
    "approve_verifications": "Aprobar Verificaciones de Identidad",
    "changes.applied": "Cambios aplicados instantáneamente a la base de datos",
    "user.notified.email": "Usuario notificado por correo electrónico",
    "audit.log.updated": "Registro de auditoría actualizado",
    "cancel": "Cancelar",
    "saving": "Guardando...",
    "saved": "Guardado",
    "never": "Nunca",
    "loading": "Cargando...",
    "no.users": "No se encontraron usuarios.",
    "pending.verification": "Verificación Pendiente",
    "more.options": "Más opciones",
    "admin.overview": "Resumen Administrativo",
    "registrar.control.panel": "Panel de Control del Registrador",
    "pending.requests": "Solicitudes Pendientes",
    "avg.lead.time": "Tiempo de Espera Promedio",
    "issued.today": "Emitidos Hoy",
    "high.urgency": "Alta Urgencia",
    "urgency.queue": "Cola de Urgencia",
    "view.all.queue": "Ver Toda la Cola",
    "requester": "Solicitante",
    "sla.status": "Estado SLA",
    "action": "Acción",
    "process.next.queue": "Procesar Siguiente en Cola",
    "review.id.verifications": "Revisar Verificaciones de ID",
    "pending.payments": "Pagos Pendientes",
    "system.status": "Estado del Sistema",
    "document.portal": "Portal de Documentos",
    "payment.gateway": "Pasarela de Pagos",
    "email.notifications": "Notificaciones por Correo",
    "online": "En Línea",
    "days": "Días",
    
    // Parent Dashboard Additions
    "parent.portal": "Portal de Padres",
    "good.morning": "Buenos días",
    "good.afternoon": "Buenas tardes",
    "good.evening": "Buenas noches",
    "parent.dashboard.subtitle": "Gestione las solicitudes de documentos académicos para sus estudiantes en la Academia Bishop Martin.",
    "identity.status": "Estado de Identidad",
    "verification.active": "Verificación activa · Válida",
    "request.doc": "Solicitar un Documento",
    "request.doc.desc": "Transcripción, Certificado y más",
    "upload.id.desc": "Subir documento de identidad",
    "email.office": "Enviar correo a nuestra oficina",
    "need.help": "¿Necesita Ayuda?",
    "office.hours.desc": "Horario de oficina: Lun–Vie, 8:00 AM – 4:00 PM (BZT). Entrega: 3–5 días hábiles.",
    "call.registrar": "Llamar al Registrador",
    "my.document.requests": "Mis Solicitudes de Documentos",
    "view.all": "Ver Todo",
    "ref": "Ref",
    "document": "Documento",
    "amount": "Monto",
    "no.requests.yet": "Aún no hay solicitudes",
    "make.first.request": "Haga su primera solicitud",

    // Traducciones adicionales
    "back.request.summary": "Volver al Resumen de la Solicitud",
    "complete.payment": "Complete su Pago",
    "payment.instructions": "Por favor, finalice su solicitud de documento iniciando una transferencia bancaria. Use los detalles a continuación para asegurar el procesamiento oportuno de sus registros académicos.",
    "bank.transfer.details": "Detalles de Transferencia Bancaria",
    "bank.name": "Nombre del Banco",
    "account.holder": "Titular de la Cuenta",
    "account.number": "Número de Cuenta",
    "branch.swift": "Sucursal / SWIFT",
    "req.ref.memo": "Memo de Referencia Obligatorio",
    "ref.memo.desc": "DEBE incluir el número de referencia de su solicitud en el campo de descripción/memo de la transferencia para evitar retrasos.",
    "next.steps": "Próximos Pasos",
    "step.initiate": "Iniciar Transferencia",
    "step.initiate.desc": "Use su aplicación bancaria o visite una sucursal de Belize Bank para enviar el monto total especificado a la cuenta anterior.",
    "step.upload": "Subir Recibo",
    "step.upload.desc": "Una vez completado, suba un PDF o foto claro de la confirmación de la transacción en el siguiente paso.",
    "step.verify": "Verificación",
    "step.verify.desc": "Nuestra oficina del tesorero verterá los fondos en un plazo de 2 a 3 días hábiles.",
    "request.summary": "Resumen de la Solicitud",
    "doc.fee": "Tarifa de Documento",
    "doc.fee.desc": "Documento académico solicitado",
    "processing.fee": "Tarifa de Procesamiento",
    "processing.fee.desc": "Velocidad de procesamiento seleccionada",
    "total.due": "Monto Total Debido",
    "confirm.initiated": "Confirmar Transferencia Iniciada",
    "confirm.initiated.desc": "Al hacer clic, se notifica a nuestro personal que los fondos están ingresando. Se le pedirá que suba el comprobante a continuación.",
    "copied": "¡copiado!",
    "back.signin": "Volver a Iniciar Sesión",
    "reset.password": "Restablecer Contraseña",
    "reset.pw.desc": "Ingrese su correo electrónico y le enviaremos un enlace de restablecimiento.",
    "send.reset.link": "Enviar Enlace de Restablecimiento",
    "check.email": "Revise su Correo",
    "reset.link.sent": "Se ha enviado un enlace de restablecimiento a",
    "check.inbox.desc": "Revise su bandeja de entrada y siga las instrucciones.",
    "create.new.pw": "Crear Nueva Contraseña",
    "strong.pw.desc": "Elija una contraseña segura para su cuenta de Bishop Martin.",
    "new.password": "Nueva Contraseña",
    "confirm.password": "Confirmar Contraseña",
    "pw.mismatch": "Las contraseñas no coinciden.",
    "resetting": "Restableciendo...",
    "legal.acknowledgement": "Reconocimiento Legal",
    "legal.text.1": "Yo, el padre/tutor abajo firmante, por la presente autorizo a la Academia Bishop Martin a divulgar los registros académicos y la documentación formal solicitados a los destinatarios especificados. Entiendo que esta firma digital tiene el mismo peso legal y validez institucional que una firma manuscrita bajo la Ley de Transacciones Electrónicas.",
    "legal.text.2": "Certifico que toda la información proporcionada en esta solicitud es precisa y que tengo la autoridad legal para autorizar la divulgación de estos registros. Reconozco que el procesamiento de esta solicitud puede implicar una verificación administrativa y que la institución se reserva el derecho de retener la documentación en casos de obligaciones financieras pendientes o verificación incompleta.",
    "legal.text.3": "Al proceder con esta firma digital, acepto el almacenamiento y procesamiento de mis datos personales con el fin de cumplir con esta solicitud de documentación de acuerdo con la política de privacidad de la institución y los estándares de gobernanza académica.",
    "legal.agree": "He leído, entendido y acepto los términos de este Reconocimiento Legal y Autorización.",
    "sig.pad": "Panel de Firma Digital",
    "sig.instruction": "Firme aquí con el ratón o el dedo",
    "sig.name.label": "Nombre Legal Completo del Firmante",
    "sig.name.placeholder": "Ingrese su nombre completo tal como aparece en su identificación",
    "cancel.request": "Cancelar Solicitud",
    "confirm.authorize": "Confirmar y Autorizar",
    "authorized": "Autorizado",
    "processing.time": "Tiempo de Procesamiento",
    "processing.time.desc": "Los documentos se emiten típicamente dentro de 3 a 5 días hábiles después de la verificación de la firma.",
    "secure.transmission": "Transmisión Segura",
    "secure.transmission.desc": "Su autorización está encriptada y almacenada en el libro administrativo de alta seguridad de la escuela.",
    "request.submitted": "¡Solicitud Enviada!",
    "request.submitted.desc": "Su solicitud de documento académico ha sido recibida y ahora está pendiente de revisión por parte de la Oficina del Registrador.",
    "ref.num": "Número de Referencia",
    "save.ref.desc": "Guarde este número para rastrear el estado de su solicitud.",
    "what.next": "Qué Sucede Después",
    "timeline.payment": "Verificación de Pago",
    "timeline.payment.desc": "Nuestra oficina del tesorero confirma su transferencia bancaria (2–3 días hábiles).",
    "timeline.processing": "Procesamiento de Documentos",
    "timeline.processing.desc": "El Registrador revisa y prepara su documento.",
    "timeline.delivery": "Envío / Notificación",
    "timeline.delivery.desc": "Recibirá un correo electrónico cuando su documento esté listo.",
    "return.dashboard": "Volver al Panel de Control",
    "upload.payment.receipt": "Subir Recibo de Pago",
    "upload.receipt.desc": "Suba una prueba clara de su transferencia bancaria. Formatos aceptados: PDF, JPG, PNG (máx. 10 MB).",
    "txn.ref.num": "Número de Referencia de Transacción",
    "txn.ref.desc": "Esto se muestra en el historial de transacciones bancarias o en el SMS de confirmación.",
    "drag.drop.receipt": "Arrastre y suelte su recibo aquí",
    "click.browse": "o haga clic para buscar archivos",
    "err.allowed.formats": "Solo se aceptan archivos PDF, JPG o PNG.",
    "err.max.size": "El archivo debe pesar menos de 10 MB.",
    "err.upload.receipt": "Por favor, suba su recibo de pago.",
    "uploaded.success": "Subido con Éxito",
    "submit.receipt": "Enviar Recibo",
    "photo.tips": "Consejos para la Foto",
    "tip.corners": "Capture Todas las Esquinas",
    "tip.corners.desc": "Asegúrese de que las cuatro esquinas del recibo sean visibles.",
    "tip.glare": "Evite Reflejos y Sombras",
    "tip.glare.desc": "Tome la foto con buena iluminación, sin reflejos.",
    "tip.level": "Manténgalo Nivelado",
    "tip.level.desc": "Sostenga la cámara paralela al documento.",
    "tip.secure": "Encriptación Segura",
    "tip.secure.desc": "Su subida está protegida con encriptación de 256 bits.",
    "payment.sent.to": "Pago enviado a:",
    "id.verification": "Verificación de Identidad",
    "id.ver.desc": "Suba una foto clara de su identificación emitida por el gobierno. Esto es requerido una sola vez para todas las futuras solicitudes de documentos.",
    "upload.id.doc": "Subir Documento de Identidad",
    "passport": "Pasaporte",
    "national.id": "Identificación Nacional",
    "drivers.license": "Licencia de Conducir",
    "voters.id": "Identificación de Votante",
    "pos.id.frame": "Posicione su identificación dentro del marco",
    "photo.guidelines": "Pautas para la Foto",
    "guideline.corners": "Capture Todas las Esquinas",
    "guideline.corners.desc": "Asegúrese de que los cuatro bordes sean visibles y no estén recortados.",
    "guideline.glare": "Evite Reflejos y Sombras",
    "guideline.glare.desc": "Iluminación buena y uniforme sin reflejos brillantes.",
    "guideline.level": "Manténgalo Nivelado",
    "guideline.level.desc": "Cámara paralela al documento, sin inclinación.",
    "guideline.secure": "Encriptado y Seguro",
    "guideline.secure.desc": "Su identificación se procesa de forma segura y nunca se comparte.",
    "err.allowed.id.formats": "Solo se aceptan archivos JPG, PNG, HEIC o PDF.",
    "err.max.id.size": "El archivo debe pesar menos de 15 MB.",
    "err.upload.id": "Por favor suba su documento de identidad.",
    "verify.continue": "Verificar y Continuar",
    "processing.verification": "Procesando Verificación",
    "stage.receiving": "Receiving document...",
    "stage.extracting": "Extracting identity data...",
    "stage.crossref": "Cross-referencing records...",
    "stage.finalizing": "Finalizing verification...",
    "percent.complete": "completado",
    "process.stay.desc": "Por favor permanezca en esta página. Esto puede tomar un momento mientras verificamos de manera segura su documento de identidad.",
    "verification.submitted": "Verificación Enviada",
    "ver.submitted.desc": "Su documento de identidad ha sido recibido de forma segura y está pendiente de revisión por el equipo administrativo del Registrador.",
    "what.expect": "Qué Esperar",
    "expect.review": "Tiempo de Revisión",
    "expect.review.desc": "Los documentos de identidad se revisan en un plazo de 1 a 2 días hábiles.",
    "expect.confirm": "Confirmación por Correo",
    "expect.confirm.desc": "Recibirá la confirmación en su dirección de correo electrónico registrada.",
    "expect.security": "Seguridad de Datos",
    "expect.security.desc": "Su documento se procesa en un entorno seguro y nunca se comparte.",
    "pending.admin.review": "Pendiente de Revisión Administrativa",
    "my.requests": "Mis Solicitudes",
    "request.history": "Historial de Solicitudes",
    "all.requests.desc": "Todas las solicitudes de documentos presentadas para sus estudiantes.",
    "search.requests": "Buscar solicitudes...",
    "no.matching.requests": "No se encontraron solicitudes coincidentes.",
    "submitted": "Enviado",
    "fee": "Tarifa",
    "request.detail": "Detalle de la Solicitud",
    "request.progress": "Progreso de la Solicitud",
    "payment.verified": "Pago Verificado",
    "delivered": "Entregado",
    "delivery": "Envío",
    "request.details": "Detalles de la Solicitud",
    "student.name": "Nombre del Estudiante",
    "grade.year": "Grado / Año",
    "recipient": "Destinatario",
    "date.submitted": "Fecha de Envío",
    "total.fee": "Tarifa Total",
    "action.required.msg": "Acción Requerida — Por favor Revise su Correo",
    "flagged.msg": "El Registrador ha marcado su solicitud. Por favor revise su correo electrónico para más detalles o contacte a la Oficina del Registrador.",
    "contact.registrar": "Contactar al Registrador",
    "ready.pickup.msg": "Su documento está listo. Por favor visite la Oficina del Registrador durante el horario de oficina (Lun-Vie 8AM-4PM) con una identificación válida.",
    "payment.summary": "Resumen de Pago",
    "total.paid": "Total Pagado",
    "email.us": "Envíenos un Correo",
    "call.us": "Llámenos",
    "pending.payments.queue": "Cola de Pagos Pendientes",
    "payments.queue.desc": "Revise los recibos de transferencia bancaria y verifique el pago de las solicitudes de documentos pendientes.",
    "no.pending.payments": "No hay pagos pendientes",
    "verify.payment": "Verificar Pago",
    "view.receipt": "Ver Recibo",
    "reg.audit.notes": "Notas de Auditoría del Registrador",
    "audit.notes.placeholder": "Agregue notas internas sobre esta solicitud (condición del documento, estado de verificación, correspondencia, etc.)...",
    "visible.staff.only": "Las notas son visibles solo para el personal.",
    "update.status": "Actualizar Estado",
    "save.status.change": "Guardar Cambio de Estado",
    "approve.release": "Aprobar y Emitir Documento",
    "flag.correction": "Marcar para Corrección",
    "sla.compliance": "SLA Compliance",
    "next.bus.day": "Siguiente Día Hábil",
    "days.2_3": "2–3 Días Hábiles",
    "days.5_7": "5–7 Días Hábiles",
    "my.profile": "Mi Perfil",
    "profile.desc": "Gestione los detalles de su cuenta y sus preferencias.",
    "member.since": "Miembro Desde",
    "email": "Correo Electrónico",
    "verification": "Verificación",
    "active.verified": "Activa · Válida",
    "edit.profile": "Editar Perfil",
    "phone.number": "Número de Teléfono",
    "email.unchangeable": "El correo electrónico no se puede cambiar. Contacte al Registrador para actualizaciones.",
    "security.password": "Seguridad y Contraseña",
    "sec.pw.desc": "Mantenga su cuenta segura usando una contraseña sólida y única.",
    "change.password": "Cambiar Contraseña",
    "new.doc.request": "Nueva Solicitud de Documento",
    "choose.doc.desc": "Elija el documento académico que necesita. Las tarifas están en dólares de Belice (BZD).",
    "saved.students": "Estudiantes Guardados",
    "or.manual.override": "O ingrese manualmente para sobrescribir:",
    "manual.fullName": "Nombre Completo *",
    "manual.studentId": "ID de Estudiante *",
    "manual.dob": "Fecha de Nacimiento",
    "manual.grade": "Año / Grado",
    "manual.relationship": "Su Relación con el Estudiante *",
    "rel.parent": "Padre / Madre",
    "rel.guardian": "Tutor Legal",
    "rel.self": "Mismo (Exalumno)",
    "rel.rep": "Representante Autorizado",
    "choose.del.desc": "Elija cómo y qué tan rápido necesita su documento.",
    "digital.delivery": "Entrega Digital",
    "pdf.sec.email": "PDF por correo electrónico seguro",
    "physical.copy": "Copia Física",
    "pickup.postal": "Recogida o correo postal",
    "std.proc": "Procesamiento Estándar",
    "std.proc.desc": "5–7 días hábiles",
    "exp.proc": "Procesamiento Expedito",
    "exp.proc.desc": "2–3 días hábiles",
    "urg.proc": "Procesamiento Urgente",
    "urg.proc.desc": "Siguiente día hábil",
    "where.send": "¿Dónde debemos enviar el documento?",
    "special.instructions": "Instrucciones Especiales (opcional)",
    "special.notes.placeholder": "Cualquier nota especial para la Oficina del Registrador...",
    "doc.requested": "Documento Solicitado",
    "review.submit": "Revisar y Enviar",
    "review.desc": "Por favor verifique todos los detalles antes de enviar su solicitud.",
    "submitting.request": "Enviando...",
    "ready.pickup": "Listo para Recogida",
    "coming.soon": "Próximamente",
    "under.development": "Esta sección está bajo desarrollo activo y estará disponible en una próxima versión.",
    "go.back": "Volver",
    "cancelled": "Cancelado",
    "toast.approved": "¡Documento aprobado y emitido!",
    "toast.flagged": "Solicitud marcada para corrección.",
    "toast.status.updated": "Estado actualizado.",
    "drag.drop.id": "Arrastre y suelte su identificación aquí",
    "remove.reupload": "Eliminar y volver a subir",
    "allowed.id.specs": "JPG · PNG · HEIC · PDF · Máx 15 MB",
    "verifying": "Verificando...",
    "requester.notes": "Notas del Solicitante",
    "request.not.found": "Solicitud no encontrada.",
    "preview.not.available": "Vista previa del documento no disponible en esta vista",
    "user.id": "ID de Usuario",
    "phone": "Teléfono",
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language: lang, setLanguage: setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
