import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    // Auth & Common
    "welcome.back": "Welcome Back",
    "login.subtitle": "Sign in to manage your academic document requests",
    "email.address": "Email Address",
    "password": "Password",
    "forgot.password": "Forgot password?",
    "sign.in": "Sign In",
    "signing.in": "Signing In...",
    "new.to.bm": "New to Bishop Martin?",
    "create.account": "Create Account",
    "phone.number": "Phone Number",
    "i.am.a": "I am a...",
    "parent.guardian": "Parent / Guardian",
    "past.student": "Past Student",
    "dob.required.note": "Past students only",
    "dob.required.err": "Date of birth is required for past students.",
    "past.student.age.error": "Past students must be 18 years or older to register.",
    "having.trouble": "Having trouble? Contact the",
    "registrar.office": "Registrar's Office",
    "privacy.policy": "Privacy Policy",
    "terms.service": "Terms of Service",
    "copyright": "Bishop Martin High School · Academic Document Request Portal",
    
    // Navigation & Layout
    "dashboard": "Dashboard",
    "requests": "Requests",
    "verification": "Verification",
    "profile": "Profile",
    "settings": "Settings",
    "logout": "Logout",
    "users": "Users",
    "admin.portal": "Admin Portal",
    "staff.portal": "Staff Portal",
    "my.profile": "My Profile",
    "view.profile": "View Profile",
    "parent.permissions.na": "Portal permissions are not applicable for parent accounts.",
    "back": "Back",
    
    // Dashboard & Actions
    "identity.verified": "Identity Verified",
    "identity.unverified": "Identity Unverified",
    "quick.actions": "Quick Actions",
    "new.request": "New Request",
    "identity.verification": "Identity Verification",
    "registrar.support": "Registrar Support",
    "recent.requests": "Recent Requests",
    "no.requests": "No requests found.",
    "document.type": "Document Type",
    "student": "Student",
    "date": "Date",
    "status": "Status",
    "actions": "Actions",
    
    // Request Flow
    "step.document": "Document",
    "step.student": "Student",
    "step.delivery": "Delivery",
    "step.review": "Review",
    "select.doc.type": "Select Document Type",
    "official.transcript": "Official Transcript",
    "enrollment.letter": "Letter of Enrollment",
    "graduation.cert": "Graduation Certificate",
    "deans.letter": "Dean's Letter",
    "other.special": "Other/Special Request",
    "lateness_form": "Lateness Form",
    "absence_form": "Absence Form",
    "lateness.form": "Lateness Form",
    "lateness.form.desc": "Lateness Form (Auto-generated slip)",
    "absence.form": "Absence Form",
    "absence.form.desc": "Absence Form (Auto-generated slip)",
    "date.of.return": "Date of Return",
    "class.grade": "Class",
    "dates.of.absence.lateness": "Date(s) of Absence/Lateness",
    "num.days.absent": "No. of days absent",
    "reason.sickness": "SICKNESS (SPECIFY)",
    "reason.traffic": "TRAFFIC (SPECIFY)",
    "reason.medical": "MEDICAL APPOINTMENT (DISMISSAL/RETURN TIME)",
    "reason.dental": "DENTAL APPOINTMENT (DISMISSAL/RETURN TIME)",
    "reason.funeral": "FUNERAL (DISMISSAL/RETURN TIME)",
    "reason.other": "OTHER (SPECIFY REASON)",
    "specify.details": "Details / Specify",
    "home.room.teacher": "Home Room Teacher",
    "auto.submission.delivery": "Digital Submission",
    "auto.submission.delivery.desc": "This form will be submitted digitally directly to the high school administration records. You do not need to choose a delivery method or pay any processing fees.",
    "form.details": "Form Details",
    "reason": "Reason",
    "reason.absence.lateness": "Reason for Absence or Lateness",
    "reason.details.time": "Dismissal / Return Time",
    "reason.details.specify": "Specify Reason",
    "form.submitted": "Form Submitted Successfully",
    "form.submitted.desc": "Your absence/lateness form has been signed, authorized, and filed directly with the school administration records.",
    "select.level": "Select Level",
    "select.number": "Select Number",
    "start.date.absence": "Start Date of Absence",
    "end.date.absence": "End Date of Absence",
    "date.of.lateness": "Date of Lateness",
    "digital.submission.no.fee": "Direct Digital Submission (No Fee)",
    "absence.form.submitted": "Absence Form Submitted",
    "absence.form.submitted.desc": "Your absence excuse form has been signed, authorized, and filed directly with the school administration records.",
    "lateness.form.submitted": "Lateness Form Submitted",
    "lateness.form.submitted.desc": "Your lateness excuse form has been signed, authorized, and filed directly with the school administration records.",
    "timeline.logged.absence": "Absence Form Logged",
    "timeline.logged.absence.desc": "The signed absence excuse has been stored securely in the school parent portal.",
    "timeline.notification.absence": "Absence Notification",
    "timeline.notification.absence.desc": "The homeroom teacher has been notified of the student's absence.",
    "timeline.status.update.absence": "Excuse Verification",
    "timeline.status.update.absence.desc": "The registrar and homeroom teacher will verify the details to excuse the absence.",
    "timeline.logged.lateness": "Lateness Form Logged",
    "timeline.logged.lateness.desc": "The signed lateness excuse has been stored securely in the school parent portal.",
    "timeline.notification.lateness": "Lateness Notification",
    "timeline.notification.lateness.desc": "The homeroom teacher has been notified of the student's tardy arrival.",
    "timeline.status.update.lateness": "Tardiness Verification",
    "timeline.status.update.lateness.desc": "The registrar and homeroom teacher will verify the details to excuse the tardy entry.",
    "timeline.logged": "Form Logged",
    "timeline.logged.desc": "The signed form has been securely stored in the school parent portal.",
    "timeline.notification": "Teacher Notification",
    "timeline.notification.desc": "The homeroom teacher has been notified of the submission.",
    "timeline.status.update": "Excuse Decision",
    "timeline.status.update.desc": "The registrar and homeroom teacher will verify the form details to excuse the absence or tardiness.",
    "file.another": "File Another Form",
    "status.excused": "Excused",
    "status.unexcused": "Unexcused",
    "status.filed.pending": "Filed - Pending Review",
    "status.filed": "Filed",
    "status.reviewed": "Reviewed",
    "filing.summary": "Filing Summary",
    "form.submission.notice": "This form has been submitted electronically directly to school records. No processing fee or payment is required.",
    "student.info": "Student Information",
    "full.name": "Full Name",
    "student.id": "Student ID",
    "dob": "Date of Birth",
    "grade": "Grade",
    "relationship": "Relationship",
    "delivery.processing": "Delivery & Processing",
    "delivery.method": "Delivery Method",
    "digital.copy": "Digital Copy (PDF via Email)",
    "physical.pickup": "Physical Pickup (In Person)",
    "processing.speed": "Processing Speed",
    "standard.speed": "Standard Processing",
    "expedited.speed": "Expedited (+ $10.00)",
    "urgent.speed": "Urgent Priority (+ $20.00)",
    "fee.breakdown": "Fee Breakdown",
    "base.fee": "Base Fee",
    "delivery.fee": "Delivery",
    "speed.fee": "Processing Speed",
    "total.fee": "Total",
    "review.sign": "Review & Authorization",
    "consent.text": "By signing below, I certify that I am the legal parent/guardian of the student listed above and authorize the release of these academic documents.",
    "sign.here": "Sign in the box below",
    "clear": "Clear",
    "submit.request": "Submit Authorization",
    "submitting": "Submitting...",
    
    // Statuses
    "pending": "Pending",
    "pending_verification": "Pending Identity Verification",
    "approved": "Approved",
    "processing": "Processing",
    "ready": "Ready",
    "issued": "Issued",
    "action.required": "Action Required",
    "rejected": "Rejected",
    
    // Settings / Dark Mode / Lang
    "theme": "Theme",
    "dark.mode": "Dark Mode",
    "light.mode": "Light Mode",
    "language": "Language",
    "english": "English",
    "spanish": "Spanish",
    "save.changes": "Save Changes",
    "queue": "Queue",
    "payments": "Payments",
    "sign.out": "Sign Out",
    "staff.access": "Staff Access",
    "super.admin": "Super Admin",
    "verify": "Verify",
    "hub": "Hub",
    "history": "History",
    "clear.filters": "Clear Filters",
    "loading.queue": "Loading queue...",
    "search.placeholder": "Search by student name, ID, or reference...",
    "all.doc.types": "All Document Types",
    "status.all": "Status: All",
    "date.received": "Date Received",
    "student.details": "Student Details",
    "no.matching.requests": "No requests found matching your filters.",
    "replacement.diploma": "Replacement Diploma",
    "user.mgmt.dir": "User Management Directory",
    "user.mgmt.subtitle": "Search and manage institutional access for staff, students, and legal guardians.",
    "invite.new.user": "Invite New User",
    "search.placeholder.user": "Name, Email, or ID Number...",
    "user.role": "User Role",
    "account.status": "Account Status",
    "all.statuses": "All Statuses",
    "active": "Active",
    "deactivated": "Deactivated",
    "last.active": "Last Active",
    "any.time": "Any Time",
    "last.7.days": "Last 7 Days",
    "requests.in.queue": "request(s) in queue",
    "request.management": "Request Management",
    "requests.subtitle": "Official document processing queue. Maintain institutional standards through meticulous verification.",
    "export.queue": "Export Queue",
    "search.student": "Search student...",
    "filter.status": "Filter Status",
    "filter.type": "Filter Type",
    
    // SuperAdmin
    "superadmin.console": "Admin Console",
    "sys.governance": "High-level system governance, server registry, and operational control.",
    "total.users": "Total Users",
    "parents": "Parents",
    "staff": "Staff",
    "super.admins": "Admins",
    "staff.registry": "Staff Registry",
    "provision.staff": "Provision Staff",
    "public.users": "Public Users",
    "search.directory": "Search Directory",
    "network.id": "Network ID",
    "identity": "Identity",
    "security.auth": "Security Auth",
    "node.termination": "Node Termination",
    "all.accounts": "All accounts",
    "registered.parents": "Registered parents",
    "admins.viewers": "Admins & viewers",
    "root.access": "Root access",
    "filter.staff": "Filter staff members...",
    "filter.public": "Filter public parent users...",
    "provision.staff.node": "Provision New Staff Node",
    "onboard.staff.member": "Onboard a new administrative staff member",
    "inst.email": "Institutional Email",
    "access.level": "Access Level",
    "level.staff": "Staff",
    "level.admin": "Admin",
    "level.viewer": "Viewer (Read-only)",
    "level.superadmin": "Admin (Root)",
    "temp.password": "Temporary Password",
    "creating.account": "Creating Account...",
    "deploy.active.account": "Deploy Active Account",
    "no.staff.nodes": "No staff nodes discovered in this sector.",
    "no.parent.users": "No parent user accounts discovered.",
    "override.password": "Override Password",
    "delete.node": "Delete Node",
    "verified": "Verified",
    "unverified": "Unverified",
    "meta.details": "Meta Details",
    "no.matching.users": "No matching user accounts discovered.",
    "password.override": "Password Override",
    "force.password.overwrite": "Forcefully overwrite password credentials for user:",
    "override.warning.msg": "This operation permanently overwrites the database security hash. The user will need to log in with this temporary password and update it immediately.",
    "temp.password.chars": "Temporary Password (min. 6 chars)",
    "executing.reset": "Executing Reset...",
    "execute.override": "Execute Override",
    "override": "Override",
    "delete": "Delete",
    "user.mgmt.dir": "User Management Directory",
    "user.mgmt.subtitle": "Search and manage institutional access for staff, students, and legal guardians.",
    "invite.new.user": "Invite New User",
    "search.placeholder.user": "Name, Email, or ID Number...",
    "user.role": "User Role",
    "account.status": "Account Status",
    "all.statuses": "All Statuses",
    "active": "Active",
    "deactivated": "Deactivated",
    "last.active": "Last Active",
    "any.time": "Any Time",
    "last.7.days": "Last 7 Days",
    "last.30.days": "Last 30 Days",
    "over.6.months": "Over 6 Months",
    "reset.filters": "Reset Filters",
    "full.directory": "Full Directory (Recent Updates)",
    "role": "Role",
    "admin": "Admin",
    "viewer": "Viewer",
    "super_admin": "Admin",
    "last.login": "Last Login",
    "user.not.found": "User not found.",
    "user.detail": "User Detail",
    "back.to.users": "Back to Users",
    "account.info": "Account Information",
    "danger.zone": "Danger Zone",
    "deactivate.account": "Deactivate Account",
    "portal.permissions": "Portal Permissions",
    "save.permissions": "Save Permissions",
    "permissions.updated": "Permissions Updated",
    "permissions.success.msg": "The user's portal permissions have been saved and will take effect on their next login.",
    "back.to.user": "Back to User",
    "all.users": "All Users",
    "invite.user.title": "Invite Portal User",
    "invite.user.subtitle": "Send an invitation to grant access to the Bishop Martin administrative portal.",
    "full.name.label": "Full Name *",
    "email.address.label": "Email Address *",
    "phone.number.label": "Phone Number",
    "portal.role.label": "Portal Role *",
    "dept.title.label": "Department / Title",
    "role.info.text": "User: Basic user like parents. Staff: Normal staff that handles every type of request or submissions. Admin: Manages all users and staff on the site. Viewer: Someone that can just see the staff portal but can't interact or change anything.",
    "send.invitation": "Send Invitation",
    "sending.invitation": "Sending...",
    "invitation.sent": "Invitation Sent!",
    "invitation.sent.to": "An invitation email has been dispatched to",
    "next.steps": "Next Steps",
    "invite.another": "Invite Another",
    "invite.step1": "The invitee will receive an email with a secure setup link.",
    "invite.step2": "They must create a password and complete account setup.",
    "invite.step3": "Permissions can be adjusted any time from User Detail.",
    "requests": "Requests",
    "payments": "Payments",
    "administration": "Administration",
    "view_requests": "View All Requests",
    "manage_requests": "Process & Update Requests",
    "approve_documents": "Approve & Release Documents",
    "view_payments": "View Payment Records",
    "verify_payments": "Verify Bank Transfers",
    "view_users": "View User Directory",
    "manage_users": "Create & Edit Users",
    "manage_permissions": "Manage Permissions",
    "view_verifications": "View ID Verifications",
    "approve_verifications": "Approve ID Verifications",
    "changes.applied": "Changes applied instantly to database",
    "user.notified.email": "User notified via email",
    "audit.log.updated": "Audit log updated",
    "cancel": "Cancel",
    "saving": "Saving...",
    "saved": "Saved",
    "never": "Never",
    "loading": "Loading...",
    "no.users": "No users found.",
    "pending.verification": "Pending Verification",
    "more.options": "More options",
    "admin.overview": "Administrative Overview",
    "registrar.control.panel": "Registrar Control Panel",
    "pending.requests": "Pending Requests",
    "avg.lead.time": "Avg. Lead Time",
    "issued.today": "Issued Today",
    "high.urgency": "High Urgency",
    "urgency.queue": "Urgency Queue",
    "view.all.queue": "View All Queue",
    "requester": "Requester",
    "sla.status": "SLA Status",
    "action": "Action",
    "process.next.queue": "Process Next in Queue",
    "review.id.verifications": "Review ID Verifications",
    "pending.payments": "Pending Payments",
    "system.status": "System Status",
    "document.portal": "Document Portal",
    "payment.gateway": "Payment Gateway",
    "email.notifications": "Email Notifications",
    "online": "Online",
    "days": "Days",
    
    // Parent Dashboard Additions
    "parent.portal": "Parent Portal",
    "good.morning": "Good morning",
    "good.afternoon": "Good afternoon",
    "good.evening": "Good evening",
    "parent.dashboard.subtitle": "Manage academic document requests for your students at Bishop Martin High School.",
    "identity.status": "Identity Status",
    "verification.active": "Verification active · Valid",
    "request.doc": "Request a Document",
    "request.doc.desc": "Transcript, Certificate & more",
    "upload.id.desc": "Upload ID document",
    "email.office": "Email our office",
    "need.help": "Need Help?",
    "office.hours.desc": "Office hours: Mon–Fri, 8:00 AM – 4:00 PM (BZT). Turnaround: 3–5 business days.",
    "call.registrar": "Call the Registrar",
    "my.document.requests": "My Document Requests",
    "view.all": "View All",
    "ref": "Ref",
    "document": "Document",
    "amount": "Amount",
    "no.requests.yet": "No requests yet",
    "make.first.request": "Make your first request",

    // Additional translations
    "back.request.summary": "Back to Request Summary",
    "complete.payment": "Complete Your Payment",
    "payment.instructions": "Please finalize your document request by initiating a bank transfer. Use the details below to ensure prompt processing of your academic records.",
    "bank.transfer.details": "Bank Transfer Details",
    "bank.name": "Bank Name",
    "account.holder": "Account Holder",
    "account.number": "Account Number",
    "branch.swift": "Branch / SWIFT",
    "req.ref.memo": "Required Reference Memo",
    "ref.memo.desc": "You MUST include your request reference number in the transfer description/memo field to avoid delays.",
    "next.steps": "Next Steps",
    "step.initiate": "Initiate Transfer",
    "step.initiate.desc": "Use your banking app or visit a Belize Bank branch to send the total amount specified to the account above.",
    "step.upload": "Upload Receipt",
    "step.upload.desc": "Once completed, upload a clear PDF or photo of the transaction confirmation in the next step.",
    "step.verify": "Verification",
    "step.verify.desc": "Our bursar's office will verify the funds within 2–3 business days.",
    "request.summary": "Request Summary",
    "doc.fee": "Document Fee",
    "doc.fee.desc": "Academic document requested",
    "processing.fee": "Processing Fee",
    "processing.fee.desc": "Selected processing speed",
    "total.due": "Total Amount Due",
    "confirm.initiated": "Confirm Transfer Initiated",
    "confirm.initiated.desc": "Clicking this notifies our staff that funds are incoming. You will be prompted to upload proof next.",
    "copied": "copied!",
    "back.signin": "Back to Sign In",
    "reset.password": "Reset Password",
    "reset.pw.desc": "Enter your email and we will send you a reset link.",
    "send.reset.link": "Send Reset Link",
    "check.email": "Check Your Email",
    "reset.link.sent": "A reset link has been sent to",
    "check.inbox.desc": "Check your inbox and follow the instructions.",
    "create.new.pw": "Create New Password",
    "strong.pw.desc": "Choose a strong password for your Bishop Martin account.",
    "new.password": "New Password",
    "confirm.password": "Confirm Password",
    "pw.mismatch": "Passwords do not match.",
    "resetting": "Resetting...",
    "legal.acknowledgement": "Legal Acknowledgement",
    "legal.text.1": "I, the undersigned parent/guardian, hereby authorize Bishop Martin High School to release the requested academic records and formal documentation to the specified recipients. I understand that this digital signature carries the same legal weight and institutional validity as a handwritten signature under the Electronic Transactions Act.",
    "legal.text.2": "I certify that all information provided in this request is accurate and that I have the legal authority to authorize the release of these records. I acknowledge that the processing of this request may involve administrative verification and that the institution reserves the right to withhold documentation in cases of outstanding financial obligations or incomplete verification.",
    "legal.text.3": "By proceeding with this digital signature, I consent to the storage and processing of my personal data for the purpose of fulfilling this documentation request in accordance with the institution's privacy policy and academic governance standards.",
    "legal.agree": "I have read, understood, and agree to the terms of this Legal Acknowledgement and Authorization.",
    "sig.pad": "Digital Signature Pad",
    "sig.instruction": "Sign here with mouse or touch",
    "sig.name.label": "Full Legal Name of Signatory",
    "sig.name.placeholder": "Enter your full name as it appears on your ID",
    "cancel.request": "Cancel Request",
    "confirm.authorize": "Confirm & Authorize",
    "authorized": "Authorized",
    "processing.time": "Processing Time",
    "processing.time.desc": "Documents are typically issued within 3–5 business days after signature verification.",
    "secure.transmission": "Secure Transmission",
    "secure.transmission.desc": "Your authorization is encrypted and stored in the school's high-security administrative ledger.",
    "request.submitted": "Request Submitted!",
    "request.submitted.desc": "Your academic document request has been received and is now pending review by the Registrar's Office.",
    "ref.num": "Reference Number",
    "save.ref.desc": "Save this number to track your request status.",
    "what.next": "What Happens Next",
    "timeline.payment": "Payment Verification",
    "timeline.payment.desc": "Our bursar's office confirms your bank transfer (2–3 business days).",
    "timeline.processing": "Document Processing",
    "timeline.processing.desc": "The Registrar reviews and prepares your document.",
    "timeline.delivery": "Delivery / Notification",
    "timeline.delivery.desc": "You'll receive an email when your document is ready.",
    "return.dashboard": "Return to Dashboard",
    "upload.payment.receipt": "Upload Payment Receipt",
    "upload.receipt.desc": "Upload clear proof of your bank transfer. Accepted formats: PDF, JPG, PNG (max 10 MB).",
    "txn.ref.num": "Transaction Reference Number",
    "txn.ref.desc": "This is shown in your bank transaction history or confirmation SMS.",
    "drag.drop.receipt": "Drag & drop your receipt here",
    "click.browse": "or click to browse files",
    "err.allowed.formats": "Only PDF, JPG, or PNG files are accepted.",
    "err.max.size": "File must be under 10 MB.",
    "err.upload.receipt": "Please upload your payment receipt.",
    "uploaded.success": "Uploaded Successfully",
    "submit.receipt": "Submit Receipt",
    "photo.tips": "Photo Tips",
    "tip.corners": "Capture All Corners",
    "tip.corners.desc": "Ensure all four corners of the receipt are visible.",
    "tip.glare": "Avoid Glare & Shadows",
    "tip.glare.desc": "Take the photo in good lighting, no reflections.",
    "tip.level": "Keep It Level",
    "tip.level.desc": "Hold the camera parallel to the document.",
    "tip.secure": "Secure Encryption",
    "tip.secure.desc": "Your upload is protected with 256-bit encryption.",
    "payment.sent.to": "Payment sent to:",
    "id.verification": "Identity Verification",
    "id.ver.desc": "Upload a clear photo of your government-issued ID. This is required once for all future document requests.",
    "upload.id.doc": "Upload ID Document",
    "passport": "Passport",
    "national.id": "National ID",
    "drivers.license": "Driver's License",
    "voters.id": "Voter's ID",
    "pos.id.frame": "Position your ID within the frame",
    "photo.guidelines": "Photo Guidelines",
    "guideline.corners": "Capture All Corners",
    "guideline.corners.desc": "Ensure all four edges are visible and unclipped.",
    "guideline.glare": "Avoid Glare & Shadows",
    "guideline.glare.desc": "Good, even lighting with no bright reflections.",
    "guideline.level": "Keep It Level",
    "guideline.level.desc": "Camera parallel to the document, no tilt.",
    "guideline.secure": "Encrypted & Secure",
    "guideline.secure.desc": "Your ID is processed securely and never shared.",
    "err.allowed.id.formats": "Only JPG, PNG, HEIC, or PDF files are accepted.",
    "err.max.id.size": "File must be under 15 MB.",
    "err.upload.id": "Please upload your identity document.",
    "verify.continue": "Verify & Continue",
    "processing.verification": "Processing Verification",
    "stage.receiving": "Receiving document...",
    "stage.extracting": "Extracting identity data...",
    "stage.crossref": "Cross-referencing records...",
    "stage.finalizing": "Finalizing verification...",
    "percent.complete": "complete",
    "process.stay.desc": "Please stay on this page. This may take a moment while we securely verify your identity document.",
    "verification.submitted": "Verification Submitted",
    "ver.submitted.desc": "Your identity document has been securely received and is pending review by the Registrar's administrative team.",
    "what.expect": "What to Expect",
    "expect.review": "Review Time",
    "expect.review.desc": "Identity documents are reviewed within 1–2 business days.",
    "expect.confirm": "Email Confirmation",
    "expect.confirm.desc": "You'll receive confirmation at your registered email address.",
    "expect.security": "Data Security",
    "expect.security.desc": "Your document is processed in a secure environment and never shared.",
    "pending.admin.review": "Pending Administrative Review",
    "my.requests": "My Requests",
    "request.history": "Request History",
    "all.requests.desc": "All document requests submitted for your students.",
    "search.requests": "Search requests...",
    "no.matching.requests": "No matching requests.",
    "submitted": "Submitted",
    "fee": "Fee",
    "request.detail": "Request Detail",
    "request.progress": "Request Progress",
    "payment.verified": "Payment Verified",
    "delivered": "Delivered",
    "delivery": "Delivery",
    "request.details": "Request Details",
    "student.name": "Student Name",
    "grade.year": "Grade / Year",
    "recipient": "Recipient",
    "date.submitted": "Date Submitted",
    "total.fee": "Total Fee",
    "action.required.msg": "Action Required — Please Check Email",
    "flagged.msg": "The Registrar has flagged your request. Please check your email for details or contact the Registrar Office.",
    "contact.registrar": "Contact Registrar",
    "ready.pickup.msg": "Your document is ready. Please visit the Registrar Office during office hours (Mon–Fri 8AM–4PM) with a valid ID.",
    "payment.summary": "Payment Summary",
    "total.paid": "Total Paid",
    "email.us": "Email Us",
    "call.us": "Call Us",
    "pending.payments.queue": "Pending Payments Queue",
    "payments.queue.desc": "Review bank transfer receipts and verify payment for pending document requests.",
    "no.pending.payments": "No pending payments",
    "verify.payment": "Verify Payment",
    "view.receipt": "View Receipt",
    "view.document": "View Uploaded Document",
    "reg.audit.notes": "Registrar Audit Notes",
    "audit.notes.placeholder": "Add internal notes about this request (document condition, verification status, correspondence, etc.)...",
    "visible.staff.only": "Notes are visible to staff only.",
    "update.status": "Update Status",
    "save.status.change": "Save Status Change",
    "approve.release": "Approve & Release Document",
    "flag.correction": "Flag for Correction",
    "sla.compliance": "SLA Compliance",
    "next.bus.day": "Next Business Day",
    "days.2_3": "2–3 Business Days",
    "days.5_7": "5–7 Business Days",
    "my.profile": "My Profile",
    "profile.desc": "Manage your account details and preferences.",
    "member.since": "Member Since",
    "email": "Email",
    "verification": "Verification",
    "active.verified": "Active · Verified",
    "edit.profile": "Edit Profile",
    "phone.number": "Phone Number",
    "email.unchangeable": "Email cannot be changed. Contact Registrar for updates.",
    "name.unchangeable": "Full name is set at registration and cannot be modified.",
    "security.password": "Security & Password",
    "sec.pw.desc": "Keep your account secure by using a strong, unique password.",
    "change.password": "Change Password",
    "new.doc.request": "New Document Request",
    "choose.doc.desc": "Choose the academic document you need. Fees are in Belize Dollars (BZD).",
    "saved.students": "Saved Students",
    "or.manual.override": "Or enter manually to override:",
    "manual.fullName": "Full Name *",
    "manual.studentId": "Student ID *",
    "manual.dob": "Date of Birth",
    "manual.grade": "Year / Grade",
    "manual.relationship": "Your Relationship to Student *",
    "rel.parent": "Parent",
    "rel.guardian": "Legal Guardian",
    "rel.legalguardian": "Legal Guardian",
    "rel.self": "Self (Alumni)",
    "rel.self(alumni)": "Self (Alumni)",
    "rel.rep": "Authorized Representative",
    "rel.authorizedrepresentative": "Authorized Representative",
    "transcript": "Official Transcript",
    "enrollment": "Letter of Enrollment",
    "graduation": "Graduation Certificate",
    "deans": "Dean's Letter",
    "diploma": "Replacement Diploma",
    "good_moral": "Good Moral Certificate",
    "other": "Other / Special Request",
    "choose.del.desc": "Choose how and how quickly you need your document.",
    "digital.delivery": "Digital Delivery",
    "pdf.sec.email": "PDF via secure email",
    "physical.copy": "Physical Copy",
    "pickup.postal": "Pickup or postal mail",
    "std.proc": "Standard Processing",
    "std.proc.desc": "5–7 business days",
    "exp.proc": "Expedited Processing",
    "exp.proc.desc": "2–3 business days",
    "urg.proc": "Urgent Processing",
    "urg.proc.desc": "Next business day",
    "where.send": "Where should we send the document?",
    "special.instructions": "Special Instructions (optional)",
    "special.notes.placeholder": "Any special notes for the Registrar's Office...",
    "doc.requested": "Document Requested",
    "review.submit": "Review & Submit",
    "review.desc": "Please verify all details before submitting your request.",
    "submitting.request": "Submitting...",
    "ready.pickup": "Ready for Pickup",
    "coming.soon": "Coming Soon",
    "under.development": "This section is under active development and will be available in an upcoming release.",
    "go.back": "Go Back",
    "cancelled": "Cancelled",
    "toast.approved": "Document approved & released!",
    "toast.flagged": "Request flagged for correction.",
    "toast.status.updated": "Status updated.",
    "drag.drop.id": "Drag & drop your ID here",
    "remove.reupload": "Remove and re-upload",
    "allowed.id.specs": "JPG · PNG · HEIC · PDF · Max 15 MB",
    "verifying": "Verifying...",
    "requester.notes": "Requester Notes",
    "request.not.found": "Request not found.",
    "preview.not.available": "Document preview not available in this view",
    "requester.notes": "Requester Notes",
    "user.id": "User ID",
    "phone": "Phone",
    "academic.doc.ready": "Academic Document Ready",
    "download.desc": "Your requested document has been issued by the institution. You can download the official copy below.",
    "official.digital.copy": "Official Digital Copy",
    "download": "Download",
    "upload.document": "Upload Final Document",
    "document.issued": "Document Issued",
    "upload.new.doc.desc": "You can upload a new version to replace the existing document.",
    "upload.doc.desc": "Upload the finalized PDF or document to automatically issue it to the parent for digital download.",
    "select.file": "Select Document File",
    "max.file.size": "PDF, images up to 20MB",
    "submit.document": "Upload & Issue Document",
    "toast.doc.uploaded": "Document uploaded and status updated to Issued.",
    "payment.summary": "Payment Summary",
    "upload.archive.desc": "Upload a scanned copy of the document for digital archiving (optional).",
    "reference.copy.disclaimer": "This is a reference copy. Please collect the official physical document.",
    "reference.digital.copy": "Reference Digital Copy",
    "toast.doc.uploaded.physical": "Document uploaded successfully for archiving.",
    "notifications": "Notifications",
    "mark.all.read": "Mark All as Read",
    "no.notifications": "No notifications yet",
    "unread.notifications": "Unread Notifications",
    "clear.all": "Clear All",
    "pricing.mgmt": "Price Management",
    "pricing.subtitle": "Update document fees dynamically",
    "base.price.bzd": "Base Price (BZD)",
    "price.updated": "Price updated successfully!",
    "price.update.fail": "Failed to update price.",
    "price.invalid": "Invalid price value.",
    "auto.generated": "Auto-generated",
    "paid.document": "Paid Document",
  },
  es: {
    // Auth & Common
    "welcome.back": "Bienvenido de Nuevo",
    "login.subtitle": "Accedé al portal para gestionar tus solicitudes de documentos académicos",
    "email.address": "Correo Electrónico",
    "password": "Contraseña",
    "forgot.password": "¿Olvidaste tu contraseña?",
    "sign.in": "Entrar",
    "signing.in": "Entrando...",
    "new.to.bm": "¿Primera vez en Bishop Martin?",
    "create.account": "Crear una Cuenta",
    "phone.number": "Número de Teléfono",
    "i.am.a": "Soy...",
    "parent.guardian": "Padre / Tutor",
    "past.student": "Exalumno/a",
    "dob.required.note": "Solo para exalumnos",
    "dob.required.err": "Los exalumnos deben indicar su fecha de nacimiento.",
    "past.student.age.error": "Los exalumnos deben tener al menos 18 años para registrarse.",
    "having.trouble": "¿Tenés problemas? Contactá la",
    "registrar.office": "Oficina del Registrador",
    "privacy.policy": "Política de Privacidad",
    "terms.service": "Términos de Uso",
    "copyright": "Bishop Martin High School · Portal de Solicitudes Académicas",
    
    // Navigation & Layout
    "dashboard": "Inicio",
    "requests": "Solicitudes",
    "verification": "Verificación",
    "profile": "Perfil",
    "settings": "Ajustes",
    "logout": "Cerrar Sesión",
    "users": "Usuarios",
    "admin.portal": "Portal Administrativo",
    "staff.portal": "Portal del Personal",
    "my.profile": "Mi Perfil",
    "view.profile": "Ver Perfil",
    "parent.permissions.na": "Los permisos del portal no aplican para cuentas de padres.",
    "back": "Atrás",
    
    // Dashboard & Actions
    "identity.verified": "Identidad Confirmada",
    "identity.unverified": "Identidad Pendiente",
    "quick.actions": "Acciones Rápidas",
    "new.request": "Nueva Solicitud",
    "identity.verification": "Verificación de Identidad",
    "registrar.support": "Contactar al Registrador",
    "recent.requests": "Solicitudes Recientes",
    "no.requests": "No hay solicitudes todavía.",
    "document.type": "Tipo de Documento",
    "student": "Estudiante",
    "date": "Fecha",
    "status": "Estado",
    "actions": "Opciones",
    
    // Request Flow
    "step.document": "Documento",
    "step.student": "Estudiante",
    "step.delivery": "Entrega",
    "step.review": "Revisión",
    "select.doc.type": "¿Qué documento necesitás?",
    "official.transcript": "Historial Académico Oficial",
    "enrollment.letter": "Carta de Matrícula",
    "graduation.cert": "Certificado de Graduación",
    "deans.letter": "Carta del Director",
    "other.special": "Otra Solicitud",
    "lateness_form": "Justificación de Tardanza",
    "absence_form": "Justificación de Ausencia",
    "lateness.form": "Justificación de Tardanza",
    "lateness.form.desc": "Justificación de Tardanza (se genera automáticamente)",
    "absence.form": "Justificación de Ausencia",
    "absence.form.desc": "Justificación de Ausencia (se genera automáticamente)",
    "date.of.return": "Fecha de Regreso",
    "class.grade": "Grado",
    "dates.of.absence.lateness": "Fecha(s) de Ausencia o Tardanza",
    "num.days.absent": "Días ausente",
    "reason.sickness": "ENFERMEDAD (ESPECIFICAR)",
    "reason.traffic": "TRÁFICO (ESPECIFICAR)",
    "reason.medical": "CITA MÉDICA (HORA DE SALIDA/REGRESO)",
    "reason.dental": "CITA DENTAL (HORA DE SALIDA/REGRESO)",
    "reason.funeral": "FUNERAL (HORA DE SALIDA/REGRESO)",
    "reason.other": "OTRO MOTIVO (ESPECIFICAR)",
    "specify.details": "Detalles adicionales",
    "home.room.teacher": "Profesor Guía",
    "auto.submission.delivery": "Envío Digital",
    "auto.submission.delivery.desc": "Este formulario se enviará directamente al sistema de registros del colegio. No necesitás elegir un método de entrega ni pagar ninguna tarifa.",
    "form.details": "Detalles del Formulario",
    "reason": "Motivo",
    "reason.absence.lateness": "Motivo de la Ausencia o Tardanza",
    "reason.details.time": "Hora de Salida / Regreso",
    "reason.details.specify": "Especificar Motivo",
    "form.submitted": "Formulario Enviado Exitosamente",
    "form.submitted.desc": "Tu justificación fue firmada, autorizada y registrada en el sistema del colegio.",
    "select.level": "Seleccionar Nivel",
    "select.number": "Seleccionar Número",
    "start.date.absence": "Inicio de la Ausencia",
    "end.date.absence": "Fin de la Ausencia",
    "date.of.lateness": "Fecha de la Tardanza",
    "digital.submission.no.fee": "Envío Digital Directo (Sin Costo)",
    "absence.form.submitted": "Justificación de Ausencia Enviada",
    "absence.form.submitted.desc": "Tu justificación fue firmada, autorizada y guardada en el sistema del colegio.",
    "lateness.form.submitted": "Justificación de Tardanza Enviada",
    "lateness.form.submitted.desc": "Tu justificación de tardanza fue firmada, autorizada y guardada en el sistema del colegio.",
    "timeline.logged.absence": "Justificación Registrada",
    "timeline.logged.absence.desc": "La justificación de ausencia firmada quedó guardada en el portal.",
    "timeline.notification.absence": "Notificación Enviada",
    "timeline.notification.absence.desc": "El profesor guía ya fue avisado de la ausencia del estudiante.",
    "timeline.status.update.absence": "Revisión de la Justificación",
    "timeline.status.update.absence.desc": "El registrador y el profesor guía revisarán la información para validar la ausencia.",
    "timeline.logged.lateness": "Tardanza Registrada",
    "timeline.logged.lateness.desc": "La justificación de tardanza firmada quedó guardada en el portal.",
    "timeline.notification.lateness": "Notificación Enviada",
    "timeline.notification.lateness.desc": "El profesor guía ya fue avisado de la tardanza del estudiante.",
    "timeline.status.update.lateness": "Revisión de la Tardanza",
    "timeline.status.update.lateness.desc": "El registrador y el profesor guía revisarán la información para validar la tardanza.",
    "timeline.logged": "Formulario Guardado",
    "timeline.logged.desc": "El formulario firmado quedó guardado de forma segura en el portal.",
    "timeline.notification": "Aviso al Profesor",
    "timeline.notification.desc": "El profesor guía fue notificado del envío.",
    "timeline.status.update": "Decisión del Colegio",
    "timeline.status.update.desc": "El registrador y el profesor guía revisarán el formulario para justificar la ausencia o tardanza.",
    "file.another": "Enviar Otro Formulario",
    "status.excused": "Justificado",
    "status.unexcused": "Sin Justificación",
    "status.filed.pending": "Enviado – Pendiente de Revisión",
    "status.filed": "Enviado",
    "status.reviewed": "Revisado",
    "filing.summary": "Resumen del Envío",
    "form.submission.notice": "Este formulario fue enviado directamente al sistema del colegio. No se requiere ningún pago.",
    "student.info": "Datos del Estudiante",
    "full.name": "Nombre Completo",
    "student.id": "Carnet del Estudiante",
    "dob": "Fecha de Nacimiento",
    "grade": "Grado",
    "relationship": "Parentesco",
    "delivery.processing": "Entrega y Procesamiento",
    "delivery.method": "Método de Entrega",
    "digital.copy": "Copia Digital (PDF al correo)",
    "physical.pickup": "Retiro en Persona",
    "processing.speed": "Velocidad de Procesamiento",
    "standard.speed": "Procesamiento Normal",
    "expedited.speed": "Rápido (+ $10.00)",
    "urgent.speed": "Urgente (+ $20.00)",
    "fee.breakdown": "Desglose de Costos",
    "base.fee": "Costo Base",
    "delivery.fee": "Entrega",
    "speed.fee": "Velocidad",
    "total.fee": "Total",
    "review.sign": "Revisión y Autorización",
    "consent.text": "Al firmar abajo, confirmo que soy el padre/tutor legal del estudiante indicado y autorizo la entrega de los documentos académicos solicitados.",
    "sign.here": "Firmá en el recuadro de abajo",
    "clear": "Borrar",
    "submit.request": "Enviar Autorización",
    "submitting": "Enviando...",
    
    // Statuses
    "pending": "Pendiente",
    "pending_verification": "Esperando Verificación de Identidad",
    "approved": "Aprobado",
    "processing": "En Proceso",
    "ready": "Listo",
    "issued": "Emitido",
    "action.required": "Requiere Atención",
    "rejected": "Rechazado",
    
    // Settings / Dark Mode / Lang
    "theme": "Apariencia",
    "dark.mode": "Modo Oscuro",
    "light.mode": "Modo Claro",
    "language": "Idioma",
    "english": "Inglés",
    "spanish": "Español",
    "save.changes": "Guardar Cambios",
    "queue": "Cola",
    "payments": "Pagos",
    "sign.out": "Cerrar Sesión",
    "staff.access": "Acceso del Personal",
    "super.admin": "Super Admin",
    "verify": "Verificar",
    "hub": "Inicio",
    "history": "Historial",
    "clear.filters": "Quitar Filtros",
    "loading.queue": "Cargando cola...",
    "search.placeholder": "Buscar por nombre, carnet o referencia...",
    "all.doc.types": "Todos los Documentos",
    "status.all": "Todos los Estados",
    "date.received": "Fecha de Recepción",
    "student.details": "Información del Estudiante",
    "no.matching.requests": "No se encontraron solicitudes con esos filtros.",
    "replacement.diploma": "Reposición de Diploma",
    "user.mgmt.dir": "Directorio de Usuarios",
    "user.mgmt.subtitle": "Buscá y administrá el acceso al portal para personal, estudiantes y tutores.",
    "invite.new.user": "Invitar Usuario",
    "search.placeholder.user": "Nombre, correo o número de ID...",
    "user.role": "Rol",
    "account.status": "Estado de la Cuenta",
    "all.statuses": "Todos los Estados",
    "active": "Activo",
    "deactivated": "Desactivado",
    "last.active": "Última Actividad",
    "any.time": "Cualquier Fecha",
    "last.7.days": "Últimos 7 Días",
    "requests.in.queue": "solicitud(es) en cola",
    "request.management": "Gestión de Solicitudes",
    "requests.subtitle": "Cola de procesamiento de documentos. Mantené los estándares del colegio con una revisión cuidadosa.",
    "export.queue": "Exportar Cola",
    "search.student": "Buscar estudiante...",
    "filter.status": "Filtrar por Estado",
    "filter.type": "Filtrar por Tipo",
    "clear.filters": "Quitar Filtros",
    
    // SuperAdmin
    "superadmin.console": "Consola de Administración",
    "sys.governance": "Control general del sistema, registro de usuarios y gestión operativa.",
    "total.users": "Total de Usuarios",
    "parents": "Padres",
    "staff": "Personal",
    "super.admins": "Administradores",
    "staff.registry": "Registro del Personal",
    "provision.staff": "Agregar Personal",
    "public.users": "Usuarios Públicos",
    "search.directory": "Buscar en el Directorio",
    "network.id": "ID de Red",
    "identity": "Identidad",
    "security.auth": "Autenticación",
    "node.termination": "Eliminar Cuenta",
    "all.accounts": "Todas las cuentas",
    "registered.parents": "Padres registrados",
    "admins.viewers": "Admins y observadores",
    "root.access": "Acceso root",
    "filter.staff": "Filtrar personal...",
    "filter.public": "Filtrar padres y usuarios...",
    "provision.staff.node": "Crear Nueva Cuenta de Personal",
    "onboard.staff.member": "Registrar a un nuevo miembro del equipo administrativo",
    "inst.email": "Correo Institucional",
    "access.level": "Nivel de Acceso",
    "level.staff": "Personal",
    "level.admin": "Administrador",
    "level.viewer": "Observador (Solo lectura)",
    "level.superadmin": "Administrador Raíz",
    "temp.password": "Contraseña Temporal",
    "creating.account": "Creando cuenta...",
    "deploy.active.account": "Crear Cuenta Activa",
    "no.staff.nodes": "No se encontró ningún miembro del personal.",
    "no.parent.users": "No se encontraron cuentas de padres.",
    "override.password": "Cambiar Contraseña",
    "delete.node": "Eliminar Cuenta",
    "verified": "Verificado",
    "unverified": "Sin Verificar",
    "meta.details": "Detalles Adicionales",
    "no.matching.users": "No se encontraron usuarios con esa búsqueda.",
    "password.override": "Restablecer Contraseña",
    "force.password.overwrite": "Cambiar forzosamente la contraseña del usuario:",
    "override.warning.msg": "Esta acción reemplaza permanentemente la contraseña en la base de datos. El usuario deberá entrar con la contraseña temporal y cambiarla de inmediato.",
    "temp.password.chars": "Contraseña Temporal (mínimo 6 caracteres)",
    "executing.reset": "Restableciendo...",
    "execute.override": "Confirmar Cambio",
    "override": "Cambiar",
    "delete": "Eliminar",
    "user.mgmt.dir": "Directorio de Usuarios",
    "user.mgmt.subtitle": "Buscá y administrá el acceso al portal para personal, estudiantes y tutores.",
    "invite.new.user": "Invitar Usuario",
    "search.placeholder.user": "Nombre, correo o número de ID...",
    "user.role": "Rol",
    "account.status": "Estado de la Cuenta",
    "all.statuses": "Todos los Estados",
    "active": "Activo",
    "deactivated": "Desactivado",
    "last.active": "Última Actividad",
    "any.time": "Cualquier Fecha",
    "last.7.days": "Últimos 7 Días",
    "last.30.days": "Últimos 30 Días",
    "over.6.months": "Más de 6 Meses",
    "reset.filters": "Restablecer Filtros",
    "full.directory": "Directorio Completo (Más Recientes)",
    "role": "Rol",
    "admin": "Administrador",
    "viewer": "Observador",
    "super_admin": "Administrador",
    "last.login": "Último Acceso",
    "user.not.found": "Usuario no encontrado.",
    "user.detail": "Detalle del Usuario",
    "back.to.users": "Volver a Usuarios",
    "account.info": "Información de la Cuenta",
    "danger.zone": "Zona de Riesgo",
    "deactivate.account": "Desactivar Cuenta",
    "portal.permissions": "Permisos del Portal",
    "save.permissions": "Guardar Permisos",
    "permissions.updated": "Permisos Actualizados",
    "permissions.success.msg": "Los permisos del usuario fueron guardados y entrarán en vigor la próxima vez que inicie sesión.",
    "back.to.user": "Volver al Usuario",
    "all.users": "Todos los Usuarios",
    "invite.user.title": "Invitar al Portal",
    "invite.user.subtitle": "Enviá una invitación para dar acceso al portal administrativo de Bishop Martin.",
    "full.name.label": "Nombre Completo *",
    "email.address.label": "Correo Electrónico *",
    "phone.number.label": "Número de Teléfono",
    "portal.role.label": "Rol en el Portal *",
    "dept.title.label": "Departamento / Cargo",
    "role.info.text": "Usuario: acceso básico, como el de los padres. Personal: gestiona todo tipo de solicitudes y envíos. Admin: administra usuarios y personal. Observador: puede ver el portal del personal pero sin hacer cambios.",
    "send.invitation": "Enviar Invitación",
    "sending.invitation": "Enviando...",
    "invitation.sent": "¡Invitación Enviada!",
    "invitation.sent.to": "Se envió un correo de invitación a",
    "next.steps": "Próximos Pasos",
    "invite.another": "Invitar a Otra Persona",
    "invite.step1": "El invitado recibirá un correo con un enlace para configurar su acceso.",
    "invite.step2": "Deberá crear su contraseña y completar el registro.",
    "invite.step3": "Los permisos se pueden ajustar en cualquier momento desde el perfil del usuario.",
    "requests": "Solicitudes",
    "payments": "Pagos",
    "administration": "Administración",
    "view_requests": "Ver Todas las Solicitudes",
    "manage_requests": "Procesar y Actualizar Solicitudes",
    "approve_documents": "Aprobar y Emitir Documentos",
    "view_payments": "Ver Registros de Pago",
    "verify_payments": "Verificar Transferencias Bancarias",
    "view_users": "Ver Directorio de Usuarios",
    "manage_users": "Crear y Editar Usuarios",
    "manage_permissions": "Administrar Permisos",
    "view_verifications": "Ver Verificaciones de Identidad",
    "approve_verifications": "Aprobar Verificaciones de Identidad",
    "changes.applied": "Cambios aplicados al instante",
    "user.notified.email": "Usuario notificado por correo",
    "audit.log.updated": "Registro de auditoría actualizado",
    "cancel": "Cancelar",
    "saving": "Guardando...",
    "saved": "Guardado",
    "never": "Nunca",
    "loading": "Cargando...",
    "no.users": "No se encontraron usuarios.",
    "pending.verification": "Verificación Pendiente",
    "more.options": "Más opciones",
    "admin.overview": "Resumen General",
    "registrar.control.panel": "Panel del Registrador",
    "pending.requests": "Solicitudes Pendientes",
    "avg.lead.time": "Tiempo Promedio de Entrega",
    "issued.today": "Emitidos Hoy",
    "high.urgency": "Alta Urgencia",
    "urgency.queue": "Cola Urgente",
    "view.all.queue": "Ver Toda la Cola",
    "requester": "Solicitante",
    "sla.status": "Estado SLA",
    "action": "Acción",
    "process.next.queue": "Procesar Siguiente",
    "review.id.verifications": "Revisar Identidades",
    "pending.payments": "Pagos Pendientes",
    "system.status": "Estado del Sistema",
    "document.portal": "Portal de Documentos",
    "payment.gateway": "Pasarela de Pagos",
    "email.notifications": "Notificaciones por Correo",
    "online": "En Línea",
    "days": "Días",
    
    // Parent Dashboard Additions
    "parent.portal": "Portal de Padres",
    "good.morning": "Buenos días",
    "good.afternoon": "Buenas tardes",
    "good.evening": "Buenas noches",
    "parent.dashboard.subtitle": "Llevá el control de los documentos académicos de tus hijos en Bishop Martin High School.",
    "identity.status": "Estado de Identidad",
    "verification.active": "Identidad verificada · Activa",
    "request.doc": "Pedir un Documento",
    "request.doc.desc": "Historial, certificados y más",
    "upload.id.desc": "Subir identificación",
    "email.office": "Escribirnos al correo",
    "need.help": "¿Necesitás Ayuda?",
    "office.hours.desc": "Horario: Lun–Vie, 8:00 AM – 4:00 PM. Entrega en 3–5 días hábiles.",
    "call.registrar": "Llamar al Registrador",
    "my.document.requests": "Mis Solicitudes",
    "view.all": "Ver Todo",
    "ref": "Ref",
    "document": "Documento",
    "amount": "Monto",
    "no.requests.yet": "Aún no tenés solicitudes",
    "make.first.request": "Hacé tu primera solicitud",

    // Traducciones adicionales
    "back.request.summary": "Volver al Resumen",
    "complete.payment": "Completar el Pago",
    "payment.instructions": "Para finalizar tu solicitud, realizá una transferencia bancaria con los datos de abajo. Incluí tu número de referencia para que podamos procesarla rápidamente.",
    "bank.transfer.details": "Datos para la Transferencia",
    "bank.name": "Banco",
    "account.holder": "Titular de la Cuenta",
    "account.number": "Número de Cuenta",
    "branch.swift": "Sucursal / SWIFT",
    "req.ref.memo": "Referencia Obligatoria en la Transferencia",
    "ref.memo.desc": "DEBÉS incluir tu número de referencia en el campo de descripción/memo de la transferencia para evitar demoras.",
    "next.steps": "Próximos Pasos",
    "step.initiate": "Hacer la Transferencia",
    "step.initiate.desc": "Usá tu app bancaria o visitá una sucursal del Belize Bank para enviar el monto indicado.",
    "step.upload": "Subir el Comprobante",
    "step.upload.desc": "Cuando termines, subí un PDF o foto clara del comprobante de la transacción.",
    "step.verify": "Verificación",
    "step.verify.desc": "El área de tesorería confirmará el pago en un plazo de 2 a 3 días hábiles.",
    "request.summary": "Resumen de la Solicitud",
    "doc.fee": "Costo del Documento",
    "doc.fee.desc": "Documento académico solicitado",
    "processing.fee": "Costo de Procesamiento",
    "processing.fee.desc": "Velocidad seleccionada",
    "total.due": "Total a Pagar",
    "confirm.initiated": "Confirmar que la Transferencia fue Realizada",
    "confirm.initiated.desc": "Al confirmar, le avisamos al personal que el pago está en camino. Luego deberás subir el comprobante.",
    "copied": "¡Copiado!",
    "back.signin": "Volver al Inicio de Sesión",
    "reset.password": "Recuperar Contraseña",
    "reset.pw.desc": "Ingresá tu correo y te enviaremos un enlace para restablecer tu contraseña.",
    "send.reset.link": "Enviar Enlace de Recuperación",
    "check.email": "Revisá tu Correo",
    "reset.link.sent": "Te enviamos un enlace de recuperación a",
    "check.inbox.desc": "Revisá tu bandeja de entrada y seguí las instrucciones.",
    "create.new.pw": "Crear Nueva Contraseña",
    "strong.pw.desc": "Elegí una contraseña segura para tu cuenta de Bishop Martin.",
    "new.password": "Nueva Contraseña",
    "confirm.password": "Confirmar Contraseña",
    "pw.mismatch": "Las contraseñas no coinciden.",
    "resetting": "Restableciendo...",
    "legal.acknowledgement": "Autorización Legal",
    "legal.text.1": "Yo, el padre/tutor abajo firmante, autorizo a Bishop Martin High School a entregar los registros académicos y documentación solicitados a los destinatarios indicados. Entiendo que esta firma digital tiene la misma validez legal que una firma manuscrita bajo la Ley de Transacciones Electrónicas.",
    "legal.text.2": "Confirmo que toda la información proporcionada es correcta y que cuento con la autoridad legal para autorizar la entrega de estos documentos. Entiendo que el procesamiento puede requerir una verificación administrativa, y que el colegio puede retener la documentación si existen obligaciones financieras pendientes o si la verificación está incompleta.",
    "legal.text.3": "Al firmar digitalmente, acepto que mis datos personales sean almacenados y utilizados para procesar esta solicitud, de acuerdo con la política de privacidad y las normas académicas del colegio.",
    "legal.agree": "Leí, entendí y acepto los términos de esta autorización.",
    "sig.pad": "Firma Digital",
    "sig.instruction": "Firmá con el dedo o el mouse",
    "sig.name.label": "Nombre Legal Completo del Firmante",
    "sig.name.placeholder": "Ingresá tu nombre tal como aparece en tu documento de identidad",
    "cancel.request": "Cancelar Solicitud",
    "confirm.authorize": "Confirmar y Autorizar",
    "authorized": "Autorizado",
    "processing.time": "Tiempo de Procesamiento",
    "processing.time.desc": "Los documentos suelen emitirse entre 3 y 5 días hábiles después de verificar la firma.",
    "secure.transmission": "Envío Seguro",
    "secure.transmission.desc": "Tu autorización está cifrada y guardada en el sistema seguro del colegio.",
    "request.submitted": "¡Solicitud Enviada!",
    "request.submitted.desc": "Tu solicitud de documento académico fue recibida y está siendo revisada por la Oficina del Registrador.",
    "ref.num": "Número de Referencia",
    "save.ref.desc": "Guardá este número para hacer seguimiento a tu solicitud.",
    "what.next": "¿Qué Pasa Ahora?",
    "timeline.payment": "Verificación del Pago",
    "timeline.payment.desc": "Tesorería confirma tu transferencia bancaria (2–3 días hábiles).",
    "timeline.processing": "Preparación del Documento",
    "timeline.processing.desc": "El Registrador revisa y prepara tu documento.",
    "timeline.delivery": "Entrega / Notificación",
    "timeline.delivery.desc": "Te avisamos por correo cuando tu documento esté listo.",
    "return.dashboard": "Volver al Inicio",
    "upload.payment.receipt": "Subir Comprobante de Pago",
    "upload.receipt.desc": "Subí una foto o PDF clara de tu comprobante. Formatos aceptados: PDF, JPG, PNG (máx. 10 MB).",
    "txn.ref.num": "Número de Referencia de la Transacción",
    "txn.ref.desc": "Podés encontrarlo en tu historial bancario o en el SMS de confirmación.",
    "drag.drop.receipt": "Arrastrá y soltá tu comprobante acá",
    "click.browse": "o hacé clic para buscar el archivo",
    "err.allowed.formats": "Solo se aceptan archivos PDF, JPG o PNG.",
    "err.max.size": "El archivo no puede superar los 10 MB.",
    "err.upload.receipt": "Por favor subí tu comprobante de pago.",
    "uploaded.success": "Subido Correctamente",
    "submit.receipt": "Enviar Comprobante",
    "photo.tips": "Consejos para la Foto",
    "tip.corners": "Mostrá Todos los Bordes",
    "tip.corners.desc": "Asegurate de que se vean las cuatro esquinas del comprobante.",
    "tip.glare": "Evitá Reflejos y Sombras",
    "tip.glare.desc": "Sacá la foto con buena iluminación y sin brillos.",
    "tip.level": "Mantenelo Derecho",
    "tip.level.desc": "La cámara debe estar paralela al documento.",
    "tip.secure": "Cifrado y Seguro",
    "tip.secure.desc": "Tu archivo está protegido con cifrado de 256 bits.",
    "payment.sent.to": "Pago enviado a:",
    "id.verification": "Verificación de Identidad",
    "id.ver.desc": "Subí una foto clara de tu documento oficial. Solo necesitás hacerlo una vez para todas tus solicitudes futuras.",
    "upload.id.doc": "Subir Documento de Identidad",
    "passport": "Pasaporte",
    "national.id": "Cédula / ID Nacional",
    "drivers.license": "Licencia de Conducir",
    "voters.id": "Carnet de Votante",
    "pos.id.frame": "Colocá tu documento dentro del recuadro",
    "photo.guidelines": "Cómo Sacar la Foto",
    "guideline.corners": "Mostrá Todos los Bordes",
    "guideline.corners.desc": "Asegurate de que se vean los cuatro bordes sin recortes.",
    "guideline.glare": "Evitá Reflejos y Sombras",
    "guideline.glare.desc": "Usá buena iluminación y evitá brillos o sombras.",
    "guideline.level": "Mantenelo Derecho",
    "guideline.level.desc": "La cámara paralela al documento, sin inclinación.",
    "guideline.secure": "Cifrado y Seguro",
    "guideline.secure.desc": "Tu documento se procesa de forma segura y nunca se comparte.",
    "err.allowed.id.formats": "Solo se aceptan archivos JPG, PNG, HEIC o PDF.",
    "err.max.id.size": "El archivo no puede superar los 15 MB.",
    "err.upload.id": "Por favor subí tu documento de identidad.",
    "verify.continue": "Verificar y Continuar",
    "processing.verification": "Procesando Verificación",
    "stage.receiving": "Recibiendo documento...",
    "stage.extracting": "Extrayendo datos de identidad...",
    "stage.crossref": "Cruzando información...",
    "stage.finalizing": "Finalizando verificación...",
    "percent.complete": "completado",
    "process.stay.desc": "Por favor no cerrés esta página. Estamos verificando tu documento de forma segura.",
    "verification.submitted": "Verificación Enviada",
    "ver.submitted.desc": "Tu documento fue recibido correctamente y está pendiente de revisión por el equipo administrativo.",
    "what.expect": "¿Qué Esperás?",
    "expect.review": "Tiempo de Revisión",
    "expect.review.desc": "Los documentos de identidad se revisan en 1 o 2 días hábiles.",
    "expect.confirm": "Confirmación por Correo",
    "expect.confirm.desc": "Te avisamos a tu correo registrado cuando esté confirmado.",
    "expect.security": "Seguridad de tus Datos",
    "expect.security.desc": "Tu documento se procesa en un entorno seguro y nunca se comparte.",
    "pending.admin.review": "En Revisión Administrativa",
    "my.requests": "Mis Solicitudes",
    "request.history": "Historial de Solicitudes",
    "all.requests.desc": "Todas las solicitudes de documentos que enviaste para tus estudiantes.",
    "search.requests": "Buscar solicitudes...",
    "no.matching.requests": "No hay solicitudes que coincidan.",
    "submitted": "Enviado",
    "fee": "Costo",
    "request.detail": "Detalle de la Solicitud",
    "request.progress": "Estado de la Solicitud",
    "payment.verified": "Pago Verificado",
    "delivered": "Entregado",
    "delivery": "Entrega",
    "request.details": "Detalles de la Solicitud",
    "student.name": "Nombre del Estudiante",
    "grade.year": "Grado / Año",
    "recipient": "Destinatario",
    "date.submitted": "Fecha de Envío",
    "total.fee": "Total",
    "action.required.msg": "Requiere Atención — Revisá tu Correo",
    "flagged.msg": "El Registrador marcó tu solicitud. Revisá tu correo para más detalles o comunicáte con la Oficina del Registrador.",
    "contact.registrar": "Contactar al Registrador",
    "ready.pickup.msg": "Tu documento está listo. Pasá por la Oficina del Registrador de lunes a viernes de 8AM a 4PM con una identificación válida.",
    "payment.summary": "Resumen del Pago",
    "total.paid": "Total Pagado",
    "email.us": "Escribirnos",
    "call.us": "Llamarnos",
    "pending.payments.queue": "Cola de Pagos Pendientes",
    "payments.queue.desc": "Revisá los comprobantes de transferencia y verificá los pagos de las solicitudes pendientes.",
    "no.pending.payments": "No hay pagos pendientes",
    "verify.payment": "Verificar Pago",
    "view.receipt": "Ver Comprobante",
    "view.document": "Ver Documento Subido",
    "reg.audit.notes": "Notas Internas del Registrador",
    "audit.notes.placeholder": "Agregá notas internas sobre esta solicitud (estado del documento, verificaciones, comunicaciones, etc.)...",
    "visible.staff.only": "Estas notas solo las ve el personal.",
    "update.status": "Actualizar Estado",
    "save.status.change": "Guardar Cambio de Estado",
    "approve.release": "Aprobar y Entregar Documento",
    "flag.correction": "Marcar para Revisión",
    "sla.compliance": "Cumplimiento SLA",
    "next.bus.day": "Próximo Día Hábil",
    "days.2_3": "2–3 Días Hábiles",
    "days.5_7": "5–7 Días Hábiles",
    "my.profile": "Mi Perfil",
    "profile.desc": "Administrá los datos de tu cuenta y tus preferencias.",
    "member.since": "Miembro Desde",
    "email": "Correo Electrónico",
    "verification": "Verificación",
    "active.verified": "Activa · Verificada",
    "edit.profile": "Editar Perfil",
    "phone.number": "Teléfono",
    "email.unchangeable": "El correo no se puede cambiar. Contactá al Registrador para actualizaciones.",
    "name.unchangeable": "El nombre se fija al registrarse y no puede modificarse.",
    "security.password": "Seguridad y Contraseña",
    "sec.pw.desc": "Usá una contraseña fuerte y única para mantener tu cuenta segura.",
    "change.password": "Cambiar Contraseña",
    "new.doc.request": "Nueva Solicitud de Documento",
    "choose.doc.desc": "Elegí el documento que necesitás. Los precios están en dólares de Belice (BZD).",
    "saved.students": "Estudiantes Guardados",
    "or.manual.override": "O ingresá los datos manualmente:",
    "manual.fullName": "Nombre Completo *",
    "manual.studentId": "Carnet del Estudiante *",
    "manual.dob": "Fecha de Nacimiento",
    "manual.grade": "Año / Grado",
    "manual.relationship": "Tu Relación con el Estudiante *",
    "rel.parent": "Padre / Madre",
    "rel.guardian": "Tutor Legal",
    "rel.legalguardian": "Tutor Legal",
    "rel.self": "Yo mismo (Exalumno)",
    "rel.self(alumni)": "Yo mismo (Exalumno)",
    "rel.rep": "Representante Autorizado",
    "rel.authorizedrepresentative": "Representante Autorizado",
    "transcript": "Historial Académico Oficial",
    "enrollment": "Carta de Matrícula",
    "graduation": "Certificado de Graduación",
    "deans": "Carta del Director",
    "diploma": "Reposición de Diploma",
    "good_moral": "Certificado de Buena Conducta",
    "other": "Otra Solicitud",
    "choose.del.desc": "Elegí cómo y con qué rapidez necesitás tu documento.",
    "digital.delivery": "Entrega Digital",
    "pdf.sec.email": "PDF al correo de forma segura",
    "physical.copy": "Copia Física",
    "pickup.postal": "Retiro en persona o por correo postal",
    "std.proc": "Procesamiento Normal",
    "std.proc.desc": "5–7 días hábiles",
    "exp.proc": "Procesamiento Rápido",
    "exp.proc.desc": "2–3 días hábiles",
    "urg.proc": "Procesamiento Urgente",
    "urg.proc.desc": "Próximo día hábil",
    "where.send": "¿A dónde enviamos el documento?",
    "special.instructions": "Instrucciones Especiales (opcional)",
    "special.notes.placeholder": "Alguna nota especial para la Oficina del Registrador...",
    "doc.requested": "Documento Solicitado",
    "review.submit": "Revisar y Enviar",
    "review.desc": "Por favor verificá todos los datos antes de enviar tu solicitud.",
    "submitting.request": "Enviando...",
    "ready.pickup": "Listo para Retirar",
    "coming.soon": "Próximamente",
    "under.development": "Esta sección está en desarrollo y estará disponible en una próxima versión.",
    "go.back": "Volver",
    "cancelled": "Cancelado",
    "toast.approved": "¡Documento aprobado y emitido!",
    "toast.flagged": "Solicitud marcada para revisión.",
    "toast.status.updated": "Estado actualizado.",
    "drag.drop.id": "Arrastrá y soltá tu identificación acá",
    "remove.reupload": "Quitar y subir de nuevo",
    "allowed.id.specs": "JPG · PNG · HEIC · PDF · Máx 15 MB",
    "verifying": "Verificando...",
    "requester.notes": "Notas del Solicitante",
    "request.not.found": "Solicitud no encontrada.",
    "preview.not.available": "La vista previa no está disponible en esta pantalla",
    "user.id": "ID de Usuario",
    "phone": "Teléfono",
    "academic.doc.ready": "Documento Académico Disponible",
    "download.desc": "Tu documento fue emitido por el colegio. Podés descargar la copia oficial abajo.",
    "official.digital.copy": "Copia Digital Oficial",
    "download": "Descargar",
    "upload.document": "Subir Documento Final",
    "document.issued": "Documento Emitido",
    "upload.new.doc.desc": "Podés subir una nueva versión para reemplazar el documento actual.",
    "upload.doc.desc": "Subí el PDF o documento final para que el padre pueda descargarlo directamente.",
    "select.file": "Seleccionar Archivo",
    "max.file.size": "PDF o imagen de hasta 20 MB",
    "submit.document": "Subir y Emitir Documento",
    "toast.doc.uploaded": "Documento subido y estado actualizado a Emitido.",
    "payment.summary": "Resumen del Pago",
    "upload.archive.desc": "Subí una copia escaneada para el archivo digital (opcional).",
    "reference.copy.disclaimer": "Esta es una copia de referencia. Retirá el documento físico oficial en el colegio.",
    "reference.digital.copy": "Copia de Referencia Digital",
    "toast.doc.uploaded.physical": "Documento subido correctamente para el archivo.",
    "notifications": "Notificaciones",
    "mark.all.read": "Marcar todo como leído",
    "no.notifications": "No hay notificaciones por el momento",
    "unread.notifications": "Notificaciones Sin Leer",
    "clear.all": "Limpiar todo",
    "pricing.mgmt": "Gestión de Precios",
    "pricing.subtitle": "Actualizá el costo de los documentos en tiempo real",
    "base.price.bzd": "Precio Base (BZD)",
    "price.updated": "¡Precio actualizado correctamente!",
    "price.update.fail": "Error al actualizar el precio.",
    "price.invalid": "El precio ingresado no es válido.",
    "auto.generated": "Autogenerado",
    "paid.document": "De Pago",
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language: lang, setLanguage: setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
